/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Rooms.RoomsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Skills.SkillsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.AbilitiesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Кастомные характеристики существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Abilities extends TableImpl<AbilitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.abilities</code>
     */
    public static final Abilities ABILITIES = new Abilities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbilitiesRecord> getRecordType() {
        return AbilitiesRecord.class;
    }

    /**
     * The column <code>rules.abilities.id</code>.
     */
    public final TableField<AbilitiesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.abilities.room_id</code>.
     */
    public final TableField<AbilitiesRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.abilities.name</code>. Название характеристики
     */
    public final TableField<AbilitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Название характеристики");

    /**
     * The column <code>rules.abilities.code</code>. Краткий код характеристики
     */
    public final TableField<AbilitiesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "Краткий код характеристики");

    private Abilities(Name alias, Table<AbilitiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Abilities(Name alias, Table<AbilitiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Кастомные характеристики существ (для homebrew игр)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.abilities</code> table reference
     */
    public Abilities(String alias) {
        this(DSL.name(alias), ABILITIES);
    }

    /**
     * Create an aliased <code>rules.abilities</code> table reference
     */
    public Abilities(Name alias) {
        this(alias, ABILITIES);
    }

    /**
     * Create a <code>rules.abilities</code> table reference
     */
    public Abilities() {
        this(DSL.name("abilities"), null);
    }

    public <O extends Record> Abilities(Table<O> path, ForeignKey<O, AbilitiesRecord> childPath, InverseForeignKey<O, AbilitiesRecord> parentPath) {
        super(path, childPath, parentPath, ABILITIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AbilitiesPath extends Abilities implements Path<AbilitiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AbilitiesPath(Table<O> path, ForeignKey<O, AbilitiesRecord> childPath, InverseForeignKey<O, AbilitiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AbilitiesPath(Name alias, Table<AbilitiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AbilitiesPath as(String alias) {
            return new AbilitiesPath(DSL.name(alias), this);
        }

        @Override
        public AbilitiesPath as(Name alias) {
            return new AbilitiesPath(alias, this);
        }

        @Override
        public AbilitiesPath as(Table<?> alias) {
            return new AbilitiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<AbilitiesRecord> getPrimaryKey() {
        return Keys.ABILITIES_PKEY;
    }

    @Override
    public List<ForeignKey<AbilitiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ABILITIES__FKABILITIES898405);
    }

    private transient RoomsPath _rooms;

    /**
     * Get the implicit join path to the <code>rules.rooms</code> table.
     */
    public RoomsPath rooms() {
        if (_rooms == null)
            _rooms = new RoomsPath(this, Keys.ABILITIES__FKABILITIES898405, null);

        return _rooms;
    }

    private transient SkillsPath _skills;

    /**
     * Get the implicit to-many join path to the <code>rules.skills</code> table
     */
    public SkillsPath skills() {
        if (_skills == null)
            _skills = new SkillsPath(this, null, Keys.SKILLS__FKSKILLS69995.getInverseKey());

        return _skills;
    }

    @Override
    public Abilities as(String alias) {
        return new Abilities(DSL.name(alias), this);
    }

    @Override
    public Abilities as(Name alias) {
        return new Abilities(alias, this);
    }

    @Override
    public Abilities as(Table<?> alias) {
        return new Abilities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Abilities rename(String name) {
        return new Abilities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Abilities rename(Name name) {
        return new Abilities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Abilities rename(Table<?> name) {
        return new Abilities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities where(Condition condition) {
        return new Abilities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Abilities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Abilities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Abilities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Abilities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Abilities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
