/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Room.RoomPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Skill.SkillPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.AbilityRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Кастомные характеристики существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Ability extends TableImpl<AbilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.ability</code>
     */
    public static final Ability ABILITY = new Ability();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbilityRecord> getRecordType() {
        return AbilityRecord.class;
    }

    /**
     * The column <code>rules.ability.id</code>.
     */
    public final TableField<AbilityRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.ability.room_id</code>.
     */
    public final TableField<AbilityRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.ability.name</code>. Название характеристики
     */
    public final TableField<AbilityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Название характеристики");

    /**
     * The column <code>rules.ability.code</code>. Краткий код характеристики
     */
    public final TableField<AbilityRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "Краткий код характеристики");

    private Ability(Name alias, Table<AbilityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Ability(Name alias, Table<AbilityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Кастомные характеристики существ (для homebrew игр)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.ability</code> table reference
     */
    public Ability(String alias) {
        this(DSL.name(alias), ABILITY);
    }

    /**
     * Create an aliased <code>rules.ability</code> table reference
     */
    public Ability(Name alias) {
        this(alias, ABILITY);
    }

    /**
     * Create a <code>rules.ability</code> table reference
     */
    public Ability() {
        this(DSL.name("ability"), null);
    }

    public <O extends Record> Ability(Table<O> path, ForeignKey<O, AbilityRecord> childPath, InverseForeignKey<O, AbilityRecord> parentPath) {
        super(path, childPath, parentPath, ABILITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AbilityPath extends Ability implements Path<AbilityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AbilityPath(Table<O> path, ForeignKey<O, AbilityRecord> childPath, InverseForeignKey<O, AbilityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AbilityPath(Name alias, Table<AbilityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AbilityPath as(String alias) {
            return new AbilityPath(DSL.name(alias), this);
        }

        @Override
        public AbilityPath as(Name alias) {
            return new AbilityPath(alias, this);
        }

        @Override
        public AbilityPath as(Table<?> alias) {
            return new AbilityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ABILITY_ROOM_ID);
    }

    @Override
    public UniqueKey<AbilityRecord> getPrimaryKey() {
        return Keys.ABILITY_PKEY;
    }

    @Override
    public List<ForeignKey<AbilityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ABILITY__FKABILITY898405);
    }

    private transient RoomPath _room;

    /**
     * Get the implicit join path to the <code>rules.room</code> table.
     */
    public RoomPath room() {
        if (_room == null)
            _room = new RoomPath(this, Keys.ABILITY__FKABILITY898405, null);

        return _room;
    }

    private transient SkillPath _skill;

    /**
     * Get the implicit to-many join path to the <code>rules.skill</code> table
     */
    public SkillPath skill() {
        if (_skill == null)
            _skill = new SkillPath(this, null, Keys.SKILL__FKSKILL69995.getInverseKey());

        return _skill;
    }

    @Override
    public Ability as(String alias) {
        return new Ability(DSL.name(alias), this);
    }

    @Override
    public Ability as(Name alias) {
        return new Ability(alias, this);
    }

    @Override
    public Ability as(Table<?> alias) {
        return new Ability(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ability rename(String name) {
        return new Ability(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ability rename(Name name) {
        return new Ability(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ability rename(Table<?> name) {
        return new Ability(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability where(Condition condition) {
        return new Ability(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ability where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ability where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ability where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Ability where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Ability whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
