/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.BackgroundTraitRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Черта происхождения (Origin Feat), даруемая предысторией
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundTrait extends TableImpl<BackgroundTraitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.background_trait</code>
     */
    public static final BackgroundTrait BACKGROUND_TRAIT = new BackgroundTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BackgroundTraitRecord> getRecordType() {
        return BackgroundTraitRecord.class;
    }

    /**
     * The column <code>rules.background_trait.id</code>.
     */
    public final TableField<BackgroundTraitRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background_trait.background_stats_id</code>.
     */
    public final TableField<BackgroundTraitRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background_trait.name</code>.
     */
    public final TableField<BackgroundTraitRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.background_trait.code</code>.
     */
    public final TableField<BackgroundTraitRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.background_trait.description</code>.
     */
    public final TableField<BackgroundTraitRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private BackgroundTrait(Name alias, Table<BackgroundTraitRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BackgroundTrait(Name alias, Table<BackgroundTraitRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Черта происхождения (Origin Feat), даруемая предысторией"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.background_trait</code> table reference
     */
    public BackgroundTrait(String alias) {
        this(DSL.name(alias), BACKGROUND_TRAIT);
    }

    /**
     * Create an aliased <code>rules.background_trait</code> table reference
     */
    public BackgroundTrait(Name alias) {
        this(alias, BACKGROUND_TRAIT);
    }

    /**
     * Create a <code>rules.background_trait</code> table reference
     */
    public BackgroundTrait() {
        this(DSL.name("background_trait"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BACKGROUND_TRAIT_STATS_ID);
    }

    @Override
    public UniqueKey<BackgroundTraitRecord> getPrimaryKey() {
        return Keys.BACKGROUND_TRAIT_PKEY;
    }

    @Override
    public BackgroundTrait as(String alias) {
        return new BackgroundTrait(DSL.name(alias), this);
    }

    @Override
    public BackgroundTrait as(Name alias) {
        return new BackgroundTrait(alias, this);
    }

    @Override
    public BackgroundTrait as(Table<?> alias) {
        return new BackgroundTrait(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundTrait rename(String name) {
        return new BackgroundTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundTrait rename(Name name) {
        return new BackgroundTrait(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundTrait rename(Table<?> name) {
        return new BackgroundTrait(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait where(Condition condition) {
        return new BackgroundTrait(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundTrait where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundTrait where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundTrait where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundTrait where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundTrait whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
