/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.BackgroundRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Предыстории
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Background extends TableImpl<BackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.background</code>
     */
    public static final Background BACKGROUND = new Background();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BackgroundRecord> getRecordType() {
        return BackgroundRecord.class;
    }

    /**
     * The column <code>rules.background.id</code>.
     */
    public final TableField<BackgroundRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background.roomid</code>.
     */
    public final TableField<BackgroundRecord, UUID> ROOMID = createField(DSL.name("roomid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background.name</code>.
     */
    public final TableField<BackgroundRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.background.description</code>.
     */
    public final TableField<BackgroundRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.background.code</code>.
     */
    public final TableField<BackgroundRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.background.img_url</code>.
     */
    public final TableField<BackgroundRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.background.background_stats_id</code>.
     */
    public final TableField<BackgroundRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Background(Name alias, Table<BackgroundRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Background(Name alias, Table<BackgroundRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Предыстории"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.background</code> table reference
     */
    public Background(String alias) {
        this(DSL.name(alias), BACKGROUND);
    }

    /**
     * Create an aliased <code>rules.background</code> table reference
     */
    public Background(Name alias) {
        this(alias, BACKGROUND);
    }

    /**
     * Create a <code>rules.background</code> table reference
     */
    public Background() {
        this(DSL.name("background"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<BackgroundRecord> getPrimaryKey() {
        return Keys.BACKGROUND_PKEY;
    }

    @Override
    public Background as(String alias) {
        return new Background(DSL.name(alias), this);
    }

    @Override
    public Background as(Name alias) {
        return new Background(alias, this);
    }

    @Override
    public Background as(Table<?> alias) {
        return new Background(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Background rename(String name) {
        return new Background(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Background rename(Name name) {
        return new Background(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Background rename(Table<?> name) {
        return new Background(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background where(Condition condition) {
        return new Background(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Background where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Background where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Background where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Background where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Background whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
