/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.BackgroundProficiencyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Владение навыком или инструментом от предыстории
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundProficiency extends TableImpl<BackgroundProficiencyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.background_proficiency</code>
     */
    public static final BackgroundProficiency BACKGROUND_PROFICIENCY = new BackgroundProficiency();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BackgroundProficiencyRecord> getRecordType() {
        return BackgroundProficiencyRecord.class;
    }

    /**
     * The column <code>rules.background_proficiency.id</code>.
     */
    public final TableField<BackgroundProficiencyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background_proficiency.background_stats_id</code>.
     */
    public final TableField<BackgroundProficiencyRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background_proficiency.type</code>. SKILL или TOOL
     */
    public final TableField<BackgroundProficiencyRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "SKILL или TOOL");

    /**
     * The column <code>rules.background_proficiency.code</code>.
     */
    public final TableField<BackgroundProficiencyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    private BackgroundProficiency(Name alias, Table<BackgroundProficiencyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BackgroundProficiency(Name alias, Table<BackgroundProficiencyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Владение навыком или инструментом от предыстории"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.background_proficiency</code> table
     * reference
     */
    public BackgroundProficiency(String alias) {
        this(DSL.name(alias), BACKGROUND_PROFICIENCY);
    }

    /**
     * Create an aliased <code>rules.background_proficiency</code> table
     * reference
     */
    public BackgroundProficiency(Name alias) {
        this(alias, BACKGROUND_PROFICIENCY);
    }

    /**
     * Create a <code>rules.background_proficiency</code> table reference
     */
    public BackgroundProficiency() {
        this(DSL.name("background_proficiency"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BACKGROUND_PROFICIENCY_STATS_ID);
    }

    @Override
    public UniqueKey<BackgroundProficiencyRecord> getPrimaryKey() {
        return Keys.BACKGROUND_PROFICIENCY_PKEY;
    }

    @Override
    public BackgroundProficiency as(String alias) {
        return new BackgroundProficiency(DSL.name(alias), this);
    }

    @Override
    public BackgroundProficiency as(Name alias) {
        return new BackgroundProficiency(alias, this);
    }

    @Override
    public BackgroundProficiency as(Table<?> alias) {
        return new BackgroundProficiency(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundProficiency rename(String name) {
        return new BackgroundProficiency(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundProficiency rename(Name name) {
        return new BackgroundProficiency(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundProficiency rename(Table<?> name) {
        return new BackgroundProficiency(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency where(Condition condition) {
        return new BackgroundProficiency(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundProficiency where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundProficiency where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundProficiency where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundProficiency where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundProficiency whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
