/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.DefaultEberronBackground.DefaultEberronBackgroundPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Background.Default_2024BackgroundPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.BackgroundStatsRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Характеристики предыстории: три характеристики на выбор (+2/+1 или +1/+1/+1)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundStats extends TableImpl<BackgroundStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.background_stats</code>
     */
    public static final BackgroundStats BACKGROUND_STATS = new BackgroundStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BackgroundStatsRecord> getRecordType() {
        return BackgroundStatsRecord.class;
    }

    /**
     * The column <code>rules.background_stats.id</code>.
     */
    public final TableField<BackgroundStatsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.background_stats.ability_modifiers</code>. Массив
     * из трёх кодов характеристик из rules.default_5e_ability (002): STR, DEX,
     * CON, INT, WIS, CHA. Источник: next.dnd.su, XPath
     * /html/body/main/div/div/div/section[2]/div/div/div[2]/ul/li[1]/text()
     * (строка «Характеристики: …»).
     */
    public final TableField<BackgroundStatsRecord, JSONB> ABILITY_MODIFIERS = createField(DSL.name("ability_modifiers"), SQLDataType.JSONB.nullable(false), this, "Массив из трёх кодов характеристик из rules.default_5e_ability (002): STR, DEX, CON, INT, WIS, CHA. Источник: next.dnd.su, XPath /html/body/main/div/div/div/section[2]/div/div/div[2]/ul/li[1]/text() (строка «Характеристики: …»).");

    private BackgroundStats(Name alias, Table<BackgroundStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BackgroundStats(Name alias, Table<BackgroundStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Характеристики предыстории: три характеристики на выбор (+2/+1 или +1/+1/+1)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.background_stats</code> table reference
     */
    public BackgroundStats(String alias) {
        this(DSL.name(alias), BACKGROUND_STATS);
    }

    /**
     * Create an aliased <code>rules.background_stats</code> table reference
     */
    public BackgroundStats(Name alias) {
        this(alias, BACKGROUND_STATS);
    }

    /**
     * Create a <code>rules.background_stats</code> table reference
     */
    public BackgroundStats() {
        this(DSL.name("background_stats"), null);
    }

    public <O extends Record> BackgroundStats(Table<O> path, ForeignKey<O, BackgroundStatsRecord> childPath, InverseForeignKey<O, BackgroundStatsRecord> parentPath) {
        super(path, childPath, parentPath, BACKGROUND_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BackgroundStatsPath extends BackgroundStats implements Path<BackgroundStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BackgroundStatsPath(Table<O> path, ForeignKey<O, BackgroundStatsRecord> childPath, InverseForeignKey<O, BackgroundStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BackgroundStatsPath(Name alias, Table<BackgroundStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BackgroundStatsPath as(String alias) {
            return new BackgroundStatsPath(DSL.name(alias), this);
        }

        @Override
        public BackgroundStatsPath as(Name alias) {
            return new BackgroundStatsPath(alias, this);
        }

        @Override
        public BackgroundStatsPath as(Table<?> alias) {
            return new BackgroundStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<BackgroundStatsRecord> getPrimaryKey() {
        return Keys.BACKGROUND_STATS_PKEY;
    }

    private transient Default_2024BackgroundPath _default_2024Background;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.default_2024_background</code> table
     */
    public Default_2024BackgroundPath default_2024Background() {
        if (_default_2024Background == null)
            _default_2024Background = new Default_2024BackgroundPath(this, null, Keys.DEFAULT_2024_BACKGROUND__FK_DEFAULT_2024_BACKGROUND_STATS.getInverseKey());

        return _default_2024Background;
    }

    private transient DefaultEberronBackgroundPath _defaultEberronBackground;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.default_eberron_background</code> table
     */
    public DefaultEberronBackgroundPath defaultEberronBackground() {
        if (_defaultEberronBackground == null)
            _defaultEberronBackground = new DefaultEberronBackgroundPath(this, null, Keys.DEFAULT_EBERRON_BACKGROUND__FK_DEFAULT_EBERRON_BACKGROUND_STATS.getInverseKey());

        return _defaultEberronBackground;
    }

    @Override
    public BackgroundStats as(String alias) {
        return new BackgroundStats(DSL.name(alias), this);
    }

    @Override
    public BackgroundStats as(Name alias) {
        return new BackgroundStats(alias, this);
    }

    @Override
    public BackgroundStats as(Table<?> alias) {
        return new BackgroundStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundStats rename(String name) {
        return new BackgroundStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundStats rename(Name name) {
        return new BackgroundStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BackgroundStats rename(Table<?> name) {
        return new BackgroundStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats where(Condition condition) {
        return new BackgroundStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BackgroundStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BackgroundStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
