/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.BlueprintRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Blueprint extends TableImpl<BlueprintRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.blueprint</code>
     */
    public static final Blueprint BLUEPRINT = new Blueprint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BlueprintRecord> getRecordType() {
        return BlueprintRecord.class;
    }

    /**
     * The column <code>rules.blueprint.id</code>.
     */
    public final TableField<BlueprintRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.blueprint.code</code>.
     */
    public final TableField<BlueprintRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.blueprint.name</code>.
     */
    public final TableField<BlueprintRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.blueprint.description</code>.
     */
    public final TableField<BlueprintRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.blueprint.group_code</code>.
     */
    public final TableField<BlueprintRecord, String> GROUP_CODE = createField(DSL.name("group_code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.blueprint.required_level</code>.
     */
    public final TableField<BlueprintRecord, Integer> REQUIRED_LEVEL = createField(DSL.name("required_level"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.blueprint.customization</code>.
     */
    public final TableField<BlueprintRecord, String> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'NO'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rules.blueprint.item_id</code>.
     */
    public final TableField<BlueprintRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>rules.blueprint.img_url</code>.
     */
    public final TableField<BlueprintRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.blueprint.bundle_id</code>.
     */
    public final TableField<BlueprintRecord, UUID> BUNDLE_ID = createField(DSL.name("bundle_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>rules.blueprint.hidden</code>.
     */
    public final TableField<BlueprintRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Blueprint(Name alias, Table<BlueprintRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Blueprint(Name alias, Table<BlueprintRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.blueprint</code> table reference
     */
    public Blueprint(String alias) {
        this(DSL.name(alias), BLUEPRINT);
    }

    /**
     * Create an aliased <code>rules.blueprint</code> table reference
     */
    public Blueprint(Name alias) {
        this(alias, BLUEPRINT);
    }

    /**
     * Create a <code>rules.blueprint</code> table reference
     */
    public Blueprint() {
        this(DSL.name("blueprint"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BLUEPRINT_BUNDLE_IDX, Indexes.BLUEPRINT_CODE_UIDX, Indexes.BLUEPRINT_GROUP_CODE_IDX);
    }

    @Override
    public UniqueKey<BlueprintRecord> getPrimaryKey() {
        return Keys.BLUEPRINT_PKEY;
    }

    @Override
    public Blueprint as(String alias) {
        return new Blueprint(DSL.name(alias), this);
    }

    @Override
    public Blueprint as(Name alias) {
        return new Blueprint(alias, this);
    }

    @Override
    public Blueprint as(Table<?> alias) {
        return new Blueprint(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Blueprint rename(String name) {
        return new Blueprint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Blueprint rename(Name name) {
        return new Blueprint(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Blueprint rename(Table<?> name) {
        return new Blueprint(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint where(Condition condition) {
        return new Blueprint(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Blueprint where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Blueprint where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Blueprint where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Blueprint where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Blueprint whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
