/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes.ClassesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClasses.Default_5eClassesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.ClassStatsRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassStats extends TableImpl<ClassStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.class_stats</code>
     */
    public static final ClassStats CLASS_STATS = new ClassStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassStatsRecord> getRecordType() {
        return ClassStatsRecord.class;
    }

    /**
     * The column <code>rules.class_stats.id</code>.
     */
    public final TableField<ClassStatsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.class_stats.hp_dice</code>.
     */
    public final TableField<ClassStatsRecord, String> HP_DICE = createField(DSL.name("hp_dice"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.class_stats.start_hp</code>.
     */
    public final TableField<ClassStatsRecord, String> START_HP = createField(DSL.name("start_hp"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.class_stats.saving_throws_abilities</code>.
     * ["WIS", "INT"]
     */
    public final TableField<ClassStatsRecord, JSONB> SAVING_THROWS_ABILITIES = createField(DSL.name("saving_throws_abilities"), SQLDataType.JSONB.nullable(false), this, "[\"WIS\", \"INT\"]");

    /**
     * The column <code>rules.class_stats.available_skills</code>. Навыки,
     * которыми может владеть класс: {"count" : 2, "list" : "WIS", "INT"}
     */
    public final TableField<ClassStatsRecord, JSONB> AVAILABLE_SKILLS = createField(DSL.name("available_skills"), SQLDataType.JSONB.nullable(false), this, "Навыки, которыми может владеть класс: {\"count\" : 2, \"list\" : \"WIS\", \"INT\"}");

    private ClassStats(Name alias, Table<ClassStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClassStats(Name alias, Table<ClassStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.class_stats</code> table reference
     */
    public ClassStats(String alias) {
        this(DSL.name(alias), CLASS_STATS);
    }

    /**
     * Create an aliased <code>rules.class_stats</code> table reference
     */
    public ClassStats(Name alias) {
        this(alias, CLASS_STATS);
    }

    /**
     * Create a <code>rules.class_stats</code> table reference
     */
    public ClassStats() {
        this(DSL.name("class_stats"), null);
    }

    public <O extends Record> ClassStats(Table<O> path, ForeignKey<O, ClassStatsRecord> childPath, InverseForeignKey<O, ClassStatsRecord> parentPath) {
        super(path, childPath, parentPath, CLASS_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClassStatsPath extends ClassStats implements Path<ClassStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClassStatsPath(Table<O> path, ForeignKey<O, ClassStatsRecord> childPath, InverseForeignKey<O, ClassStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClassStatsPath(Name alias, Table<ClassStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClassStatsPath as(String alias) {
            return new ClassStatsPath(DSL.name(alias), this);
        }

        @Override
        public ClassStatsPath as(Name alias) {
            return new ClassStatsPath(alias, this);
        }

        @Override
        public ClassStatsPath as(Table<?> alias) {
            return new ClassStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<ClassStatsRecord> getPrimaryKey() {
        return Keys.CLASS_STATS_PKEY;
    }

    private transient ClassesPath _classes;

    /**
     * Get the implicit to-many join path to the <code>rules.classes</code>
     * table
     */
    public ClassesPath classes() {
        if (_classes == null)
            _classes = new ClassesPath(this, null, Keys.CLASSES__FKCLASSES375368.getInverseKey());

        return _classes;
    }

    private transient Default_5eClassesPath _default_5eClasses;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.default_5e_classes</code> table
     */
    public Default_5eClassesPath default_5eClasses() {
        if (_default_5eClasses == null)
            _default_5eClasses = new Default_5eClassesPath(this, null, Keys.DEFAULT_5E_CLASSES__FKDEFAULT_5E174476.getInverseKey());

        return _default_5eClasses;
    }

    @Override
    public ClassStats as(String alias) {
        return new ClassStats(DSL.name(alias), this);
    }

    @Override
    public ClassStats as(Name alias) {
        return new ClassStats(alias, this);
    }

    @Override
    public ClassStats as(Table<?> alias) {
        return new ClassStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassStats rename(String name) {
        return new ClassStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassStats rename(Name name) {
        return new ClassStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassStats rename(Table<?> name) {
        return new ClassStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats where(Condition condition) {
        return new ClassStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
