/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats.ClassStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.ClassProficienciesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassProficiencies extends TableImpl<ClassProficienciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.class_proficiencies</code>
     */
    public static final ClassProficiencies CLASS_PROFICIENCIES = new ClassProficiencies();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassProficienciesRecord> getRecordType() {
        return ClassProficienciesRecord.class;
    }

    /**
     * The column <code>rules.class_proficiencies.id</code>.
     */
    public final TableField<ClassProficienciesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.class_proficiencies.class_stats_id</code>.
     */
    public final TableField<ClassProficienciesRecord, UUID> CLASS_STATS_ID = createField(DSL.name("class_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.class_proficiencies.type</code>.
     */
    public final TableField<ClassProficienciesRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.class_proficiencies.code</code>.
     */
    public final TableField<ClassProficienciesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    private ClassProficiencies(Name alias, Table<ClassProficienciesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClassProficiencies(Name alias, Table<ClassProficienciesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.class_proficiencies</code> table reference
     */
    public ClassProficiencies(String alias) {
        this(DSL.name(alias), CLASS_PROFICIENCIES);
    }

    /**
     * Create an aliased <code>rules.class_proficiencies</code> table reference
     */
    public ClassProficiencies(Name alias) {
        this(alias, CLASS_PROFICIENCIES);
    }

    /**
     * Create a <code>rules.class_proficiencies</code> table reference
     */
    public ClassProficiencies() {
        this(DSL.name("class_proficiencies"), null);
    }

    public <O extends Record> ClassProficiencies(Table<O> path, ForeignKey<O, ClassProficienciesRecord> childPath, InverseForeignKey<O, ClassProficienciesRecord> parentPath) {
        super(path, childPath, parentPath, CLASS_PROFICIENCIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClassProficienciesPath extends ClassProficiencies implements Path<ClassProficienciesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClassProficienciesPath(Table<O> path, ForeignKey<O, ClassProficienciesRecord> childPath, InverseForeignKey<O, ClassProficienciesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClassProficienciesPath(Name alias, Table<ClassProficienciesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClassProficienciesPath as(String alias) {
            return new ClassProficienciesPath(DSL.name(alias), this);
        }

        @Override
        public ClassProficienciesPath as(Name alias) {
            return new ClassProficienciesPath(alias, this);
        }

        @Override
        public ClassProficienciesPath as(Table<?> alias) {
            return new ClassProficienciesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<ClassProficienciesRecord> getPrimaryKey() {
        return Keys.CLASS_PROFICIENCIES_PKEY;
    }

    @Override
    public List<ForeignKey<ClassProficienciesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLASS_PROFICIENCIES__FKCLASS_PROF188640);
    }

    private transient ClassStatsPath _classStats;

    /**
     * Get the implicit join path to the <code>rules.class_stats</code> table.
     */
    public ClassStatsPath classStats() {
        if (_classStats == null)
            _classStats = new ClassStatsPath(this, Keys.CLASS_PROFICIENCIES__FKCLASS_PROF188640, null);

        return _classStats;
    }

    @Override
    public ClassProficiencies as(String alias) {
        return new ClassProficiencies(DSL.name(alias), this);
    }

    @Override
    public ClassProficiencies as(Name alias) {
        return new ClassProficiencies(alias, this);
    }

    @Override
    public ClassProficiencies as(Table<?> alias) {
        return new ClassProficiencies(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassProficiencies rename(String name) {
        return new ClassProficiencies(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassProficiencies rename(Name name) {
        return new ClassProficiencies(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClassProficiencies rename(Table<?> name) {
        return new ClassProficiencies(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies where(Condition condition) {
        return new ClassProficiencies(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassProficiencies where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassProficiencies where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassProficiencies where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClassProficiencies where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClassProficiencies whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
