/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eRaceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eRace extends TableImpl<Default_5eRaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_race</code>
     */
    public static final Default_5eRace DEFAULT_5E_RACE = new Default_5eRace();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eRaceRecord> getRecordType() {
        return Default_5eRaceRecord.class;
    }

    /**
     * The column <code>rules.default_5e_race.id</code>.
     */
    public final TableField<Default_5eRaceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_race.name</code>.
     */
    public final TableField<Default_5eRaceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_race.description</code>.
     */
    public final TableField<Default_5eRaceRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_5e_race.code</code>.
     */
    public final TableField<Default_5eRaceRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_race.race_stats_id</code>.
     */
    public final TableField<Default_5eRaceRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Default_5eRace(Name alias, Table<Default_5eRaceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eRace(Name alias, Table<Default_5eRaceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_race</code> table reference
     */
    public Default_5eRace(String alias) {
        this(DSL.name(alias), DEFAULT_5E_RACE);
    }

    /**
     * Create an aliased <code>rules.default_5e_race</code> table reference
     */
    public Default_5eRace(Name alias) {
        this(alias, DEFAULT_5E_RACE);
    }

    /**
     * Create a <code>rules.default_5e_race</code> table reference
     */
    public Default_5eRace() {
        this(DSL.name("default_5e_race"), null);
    }

    public <O extends Record> Default_5eRace(Table<O> path, ForeignKey<O, Default_5eRaceRecord> childPath, InverseForeignKey<O, Default_5eRaceRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_RACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eRacePath extends Default_5eRace implements Path<Default_5eRaceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eRacePath(Table<O> path, ForeignKey<O, Default_5eRaceRecord> childPath, InverseForeignKey<O, Default_5eRaceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eRacePath(Name alias, Table<Default_5eRaceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eRacePath as(String alias) {
            return new Default_5eRacePath(DSL.name(alias), this);
        }

        @Override
        public Default_5eRacePath as(Name alias) {
            return new Default_5eRacePath(alias, this);
        }

        @Override
        public Default_5eRacePath as(Table<?> alias) {
            return new Default_5eRacePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eRaceRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_RACE_PKEY;
    }

    @Override
    public List<ForeignKey<Default_5eRaceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_5E_RACE__FKDEFAULT_5E40267);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.DEFAULT_5E_RACE__FKDEFAULT_5E40267, null);

        return _raceStats;
    }

    @Override
    public Default_5eRace as(String alias) {
        return new Default_5eRace(DSL.name(alias), this);
    }

    @Override
    public Default_5eRace as(Name alias) {
        return new Default_5eRace(alias, this);
    }

    @Override
    public Default_5eRace as(Table<?> alias) {
        return new Default_5eRace(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRace rename(String name) {
        return new Default_5eRace(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRace rename(Name name) {
        return new Default_5eRace(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRace rename(Table<?> name) {
        return new Default_5eRace(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace where(Condition condition) {
        return new Default_5eRace(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRace where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRace where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRace where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRace where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRace whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
