/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats.ClassStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eClassesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eClasses extends TableImpl<Default_5eClassesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_classes</code>
     */
    public static final Default_5eClasses DEFAULT_5E_CLASSES = new Default_5eClasses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eClassesRecord> getRecordType() {
        return Default_5eClassesRecord.class;
    }

    /**
     * The column <code>rules.default_5e_classes.id</code>.
     */
    public final TableField<Default_5eClassesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_classes.name</code>.
     */
    public final TableField<Default_5eClassesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_classes.code</code>.
     */
    public final TableField<Default_5eClassesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_classes.class_stats_id</code>.
     */
    public final TableField<Default_5eClassesRecord, UUID> CLASS_STATS_ID = createField(DSL.name("class_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Default_5eClasses(Name alias, Table<Default_5eClassesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eClasses(Name alias, Table<Default_5eClassesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_classes</code> table reference
     */
    public Default_5eClasses(String alias) {
        this(DSL.name(alias), DEFAULT_5E_CLASSES);
    }

    /**
     * Create an aliased <code>rules.default_5e_classes</code> table reference
     */
    public Default_5eClasses(Name alias) {
        this(alias, DEFAULT_5E_CLASSES);
    }

    /**
     * Create a <code>rules.default_5e_classes</code> table reference
     */
    public Default_5eClasses() {
        this(DSL.name("default_5e_classes"), null);
    }

    public <O extends Record> Default_5eClasses(Table<O> path, ForeignKey<O, Default_5eClassesRecord> childPath, InverseForeignKey<O, Default_5eClassesRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_CLASSES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eClassesPath extends Default_5eClasses implements Path<Default_5eClassesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eClassesPath(Table<O> path, ForeignKey<O, Default_5eClassesRecord> childPath, InverseForeignKey<O, Default_5eClassesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eClassesPath(Name alias, Table<Default_5eClassesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eClassesPath as(String alias) {
            return new Default_5eClassesPath(DSL.name(alias), this);
        }

        @Override
        public Default_5eClassesPath as(Name alias) {
            return new Default_5eClassesPath(alias, this);
        }

        @Override
        public Default_5eClassesPath as(Table<?> alias) {
            return new Default_5eClassesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eClassesRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_CLASSES_PKEY;
    }

    @Override
    public List<ForeignKey<Default_5eClassesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_5E_CLASSES__FKDEFAULT_5E174476);
    }

    private transient ClassStatsPath _classStats;

    /**
     * Get the implicit join path to the <code>rules.class_stats</code> table.
     */
    public ClassStatsPath classStats() {
        if (_classStats == null)
            _classStats = new ClassStatsPath(this, Keys.DEFAULT_5E_CLASSES__FKDEFAULT_5E174476, null);

        return _classStats;
    }

    @Override
    public Default_5eClasses as(String alias) {
        return new Default_5eClasses(DSL.name(alias), this);
    }

    @Override
    public Default_5eClasses as(Name alias) {
        return new Default_5eClasses(alias, this);
    }

    @Override
    public Default_5eClasses as(Table<?> alias) {
        return new Default_5eClasses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClasses rename(String name) {
        return new Default_5eClasses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClasses rename(Name name) {
        return new Default_5eClasses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClasses rename(Table<?> name) {
        return new Default_5eClasses(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses where(Condition condition) {
        return new Default_5eClasses(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClasses where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClasses where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClasses where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClasses where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClasses whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
