/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkills.Default_5eSkillsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eAbilitiesRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Характеристики существ по дефолтным правилам ДнД 5е
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eAbilities extends TableImpl<Default_5eAbilitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_abilities</code>
     */
    public static final Default_5eAbilities DEFAULT_5E_ABILITIES = new Default_5eAbilities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eAbilitiesRecord> getRecordType() {
        return Default_5eAbilitiesRecord.class;
    }

    /**
     * The column <code>rules.default_5e_abilities.id</code>.
     */
    public final TableField<Default_5eAbilitiesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_abilities.name</code>. Название
     * Характеристики
     */
    public final TableField<Default_5eAbilitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Название Характеристики");

    /**
     * The column <code>rules.default_5e_abilities.code</code>. Краткий код
     * Характеристики
     */
    public final TableField<Default_5eAbilitiesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "Краткий код Характеристики");

    private Default_5eAbilities(Name alias, Table<Default_5eAbilitiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eAbilities(Name alias, Table<Default_5eAbilitiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Характеристики существ по дефолтным правилам ДнД 5е"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_abilities</code> table reference
     */
    public Default_5eAbilities(String alias) {
        this(DSL.name(alias), DEFAULT_5E_ABILITIES);
    }

    /**
     * Create an aliased <code>rules.default_5e_abilities</code> table reference
     */
    public Default_5eAbilities(Name alias) {
        this(alias, DEFAULT_5E_ABILITIES);
    }

    /**
     * Create a <code>rules.default_5e_abilities</code> table reference
     */
    public Default_5eAbilities() {
        this(DSL.name("default_5e_abilities"), null);
    }

    public <O extends Record> Default_5eAbilities(Table<O> path, ForeignKey<O, Default_5eAbilitiesRecord> childPath, InverseForeignKey<O, Default_5eAbilitiesRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_ABILITIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eAbilitiesPath extends Default_5eAbilities implements Path<Default_5eAbilitiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eAbilitiesPath(Table<O> path, ForeignKey<O, Default_5eAbilitiesRecord> childPath, InverseForeignKey<O, Default_5eAbilitiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eAbilitiesPath(Name alias, Table<Default_5eAbilitiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eAbilitiesPath as(String alias) {
            return new Default_5eAbilitiesPath(DSL.name(alias), this);
        }

        @Override
        public Default_5eAbilitiesPath as(Name alias) {
            return new Default_5eAbilitiesPath(alias, this);
        }

        @Override
        public Default_5eAbilitiesPath as(Table<?> alias) {
            return new Default_5eAbilitiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eAbilitiesRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_ABILITIES_PKEY;
    }

    private transient Default_5eSkillsPath _default_5eSkills;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.default_5e_skills</code> table
     */
    public Default_5eSkillsPath default_5eSkills() {
        if (_default_5eSkills == null)
            _default_5eSkills = new Default_5eSkillsPath(this, null, Keys.DEFAULT_5E_SKILLS__FKDEFAULT_5E869303.getInverseKey());

        return _default_5eSkills;
    }

    @Override
    public Default_5eAbilities as(String alias) {
        return new Default_5eAbilities(DSL.name(alias), this);
    }

    @Override
    public Default_5eAbilities as(Name alias) {
        return new Default_5eAbilities(alias, this);
    }

    @Override
    public Default_5eAbilities as(Table<?> alias) {
        return new Default_5eAbilities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eAbilities rename(String name) {
        return new Default_5eAbilities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eAbilities rename(Name name) {
        return new Default_5eAbilities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eAbilities rename(Table<?> name) {
        return new Default_5eAbilities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities where(Condition condition) {
        return new Default_5eAbilities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eAbilities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eAbilities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eAbilities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eAbilities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eAbilities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
