/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbilities.Default_5eAbilitiesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eSkillsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Навыки по дефолтным правилам DnD 5e
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eSkills extends TableImpl<Default_5eSkillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_skills</code>
     */
    public static final Default_5eSkills DEFAULT_5E_SKILLS = new Default_5eSkills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eSkillsRecord> getRecordType() {
        return Default_5eSkillsRecord.class;
    }

    /**
     * The column <code>rules.default_5e_skills.id</code>.
     */
    public final TableField<Default_5eSkillsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_skills.name</code>. Название навыка
     */
    public final TableField<Default_5eSkillsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Название навыка");

    /**
     * The column <code>rules.default_5e_skills.code</code>. Краткий код навыка
     */
    public final TableField<Default_5eSkillsRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "Краткий код навыка");

    /**
     * The column <code>rules.default_5e_skills.depend_on_ability</code>.
     * Зависимость навыка от характеристики
     */
    public final TableField<Default_5eSkillsRecord, UUID> DEPEND_ON_ABILITY = createField(DSL.name("depend_on_ability"), SQLDataType.UUID.nullable(false), this, "Зависимость навыка от характеристики");

    private Default_5eSkills(Name alias, Table<Default_5eSkillsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eSkills(Name alias, Table<Default_5eSkillsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Навыки по дефолтным правилам DnD 5e"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_skills</code> table reference
     */
    public Default_5eSkills(String alias) {
        this(DSL.name(alias), DEFAULT_5E_SKILLS);
    }

    /**
     * Create an aliased <code>rules.default_5e_skills</code> table reference
     */
    public Default_5eSkills(Name alias) {
        this(alias, DEFAULT_5E_SKILLS);
    }

    /**
     * Create a <code>rules.default_5e_skills</code> table reference
     */
    public Default_5eSkills() {
        this(DSL.name("default_5e_skills"), null);
    }

    public <O extends Record> Default_5eSkills(Table<O> path, ForeignKey<O, Default_5eSkillsRecord> childPath, InverseForeignKey<O, Default_5eSkillsRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_SKILLS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eSkillsPath extends Default_5eSkills implements Path<Default_5eSkillsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eSkillsPath(Table<O> path, ForeignKey<O, Default_5eSkillsRecord> childPath, InverseForeignKey<O, Default_5eSkillsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eSkillsPath(Name alias, Table<Default_5eSkillsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eSkillsPath as(String alias) {
            return new Default_5eSkillsPath(DSL.name(alias), this);
        }

        @Override
        public Default_5eSkillsPath as(Name alias) {
            return new Default_5eSkillsPath(alias, this);
        }

        @Override
        public Default_5eSkillsPath as(Table<?> alias) {
            return new Default_5eSkillsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eSkillsRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_SKILLS_PKEY;
    }

    @Override
    public List<ForeignKey<Default_5eSkillsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_5E_SKILLS__FKDEFAULT_5E869303);
    }

    private transient Default_5eAbilitiesPath _default_5eAbilities;

    /**
     * Get the implicit join path to the <code>rules.default_5e_abilities</code>
     * table.
     */
    public Default_5eAbilitiesPath default_5eAbilities() {
        if (_default_5eAbilities == null)
            _default_5eAbilities = new Default_5eAbilitiesPath(this, Keys.DEFAULT_5E_SKILLS__FKDEFAULT_5E869303, null);

        return _default_5eAbilities;
    }

    @Override
    public Default_5eSkills as(String alias) {
        return new Default_5eSkills(DSL.name(alias), this);
    }

    @Override
    public Default_5eSkills as(Name alias) {
        return new Default_5eSkills(alias, this);
    }

    @Override
    public Default_5eSkills as(Table<?> alias) {
        return new Default_5eSkills(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eSkills rename(String name) {
        return new Default_5eSkills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eSkills rename(Name name) {
        return new Default_5eSkills(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eSkills rename(Table<?> name) {
        return new Default_5eSkills(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills where(Condition condition) {
        return new Default_5eSkills(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eSkills where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eSkills where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eSkills where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eSkills where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eSkills whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
