/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eRacesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eRaces extends TableImpl<Default_5eRacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_races</code>
     */
    public static final Default_5eRaces DEFAULT_5E_RACES = new Default_5eRaces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eRacesRecord> getRecordType() {
        return Default_5eRacesRecord.class;
    }

    /**
     * The column <code>rules.default_5e_races.id</code>.
     */
    public final TableField<Default_5eRacesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_races.name</code>.
     */
    public final TableField<Default_5eRacesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_races.description</code>.
     */
    public final TableField<Default_5eRacesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_5e_races.code</code>.
     */
    public final TableField<Default_5eRacesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_races.race_stats_id</code>.
     */
    public final TableField<Default_5eRacesRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Default_5eRaces(Name alias, Table<Default_5eRacesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eRaces(Name alias, Table<Default_5eRacesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_races</code> table reference
     */
    public Default_5eRaces(String alias) {
        this(DSL.name(alias), DEFAULT_5E_RACES);
    }

    /**
     * Create an aliased <code>rules.default_5e_races</code> table reference
     */
    public Default_5eRaces(Name alias) {
        this(alias, DEFAULT_5E_RACES);
    }

    /**
     * Create a <code>rules.default_5e_races</code> table reference
     */
    public Default_5eRaces() {
        this(DSL.name("default_5e_races"), null);
    }

    public <O extends Record> Default_5eRaces(Table<O> path, ForeignKey<O, Default_5eRacesRecord> childPath, InverseForeignKey<O, Default_5eRacesRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_RACES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eRacesPath extends Default_5eRaces implements Path<Default_5eRacesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eRacesPath(Table<O> path, ForeignKey<O, Default_5eRacesRecord> childPath, InverseForeignKey<O, Default_5eRacesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eRacesPath(Name alias, Table<Default_5eRacesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eRacesPath as(String alias) {
            return new Default_5eRacesPath(DSL.name(alias), this);
        }

        @Override
        public Default_5eRacesPath as(Name alias) {
            return new Default_5eRacesPath(alias, this);
        }

        @Override
        public Default_5eRacesPath as(Table<?> alias) {
            return new Default_5eRacesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eRacesRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_RACES_PKEY;
    }

    @Override
    public List<ForeignKey<Default_5eRacesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_5E_RACES__FKDEFAULT_5E40267);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.DEFAULT_5E_RACES__FKDEFAULT_5E40267, null);

        return _raceStats;
    }

    @Override
    public Default_5eRaces as(String alias) {
        return new Default_5eRaces(DSL.name(alias), this);
    }

    @Override
    public Default_5eRaces as(Name alias) {
        return new Default_5eRaces(alias, this);
    }

    @Override
    public Default_5eRaces as(Table<?> alias) {
        return new Default_5eRaces(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRaces rename(String name) {
        return new Default_5eRaces(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRaces rename(Name name) {
        return new Default_5eRaces(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eRaces rename(Table<?> name) {
        return new Default_5eRaces(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces where(Condition condition) {
        return new Default_5eRaces(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRaces where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRaces where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRaces where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eRaces where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eRaces whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
