/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.DefaultStatesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultStates extends TableImpl<DefaultStatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_states</code>
     */
    public static final DefaultStates DEFAULT_STATES = new DefaultStates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DefaultStatesRecord> getRecordType() {
        return DefaultStatesRecord.class;
    }

    /**
     * The column <code>rules.default_states.id</code>.
     */
    public final TableField<DefaultStatesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_states.name</code>.
     */
    public final TableField<DefaultStatesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_states.code</code>.
     */
    public final TableField<DefaultStatesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_states.description</code>.
     */
    public final TableField<DefaultStatesRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private DefaultStates(Name alias, Table<DefaultStatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DefaultStates(Name alias, Table<DefaultStatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_states</code> table reference
     */
    public DefaultStates(String alias) {
        this(DSL.name(alias), DEFAULT_STATES);
    }

    /**
     * Create an aliased <code>rules.default_states</code> table reference
     */
    public DefaultStates(Name alias) {
        this(alias, DEFAULT_STATES);
    }

    /**
     * Create a <code>rules.default_states</code> table reference
     */
    public DefaultStates() {
        this(DSL.name("default_states"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<DefaultStatesRecord> getPrimaryKey() {
        return Keys.DEFAULT_STATES_PK;
    }

    @Override
    public List<UniqueKey<DefaultStatesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DEFAULT_STATES_CODE_UQ);
    }

    @Override
    public DefaultStates as(String alias) {
        return new DefaultStates(DSL.name(alias), this);
    }

    @Override
    public DefaultStates as(Name alias) {
        return new DefaultStates(alias, this);
    }

    @Override
    public DefaultStates as(Table<?> alias) {
        return new DefaultStates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultStates rename(String name) {
        return new DefaultStates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultStates rename(Name name) {
        return new DefaultStates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultStates rename(Table<?> name) {
        return new DefaultStates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates where(Condition condition) {
        return new DefaultStates(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultStates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultStates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultStates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultStates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultStates whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
