/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_2024RaceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_2024Race extends TableImpl<Default_2024RaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_2024_race</code>
     */
    public static final Default_2024Race DEFAULT_2024_RACE = new Default_2024Race();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_2024RaceRecord> getRecordType() {
        return Default_2024RaceRecord.class;
    }

    /**
     * The column <code>rules.default_2024_race.id</code>.
     */
    public final TableField<Default_2024RaceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_race.name</code>.
     */
    public final TableField<Default_2024RaceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_race.description</code>.
     */
    public final TableField<Default_2024RaceRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_2024_race.code</code>.
     */
    public final TableField<Default_2024RaceRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_race.race_stats_id</code>.
     */
    public final TableField<Default_2024RaceRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_race.img_url</code>.
     */
    public final TableField<Default_2024RaceRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.default_2024_race.species_code</code>.
     */
    public final TableField<Default_2024RaceRecord, String> SPECIES_CODE = createField(DSL.name("species_code"), SQLDataType.VARCHAR, this, "");

    private Default_2024Race(Name alias, Table<Default_2024RaceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_2024Race(Name alias, Table<Default_2024RaceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_2024_race</code> table reference
     */
    public Default_2024Race(String alias) {
        this(DSL.name(alias), DEFAULT_2024_RACE);
    }

    /**
     * Create an aliased <code>rules.default_2024_race</code> table reference
     */
    public Default_2024Race(Name alias) {
        this(alias, DEFAULT_2024_RACE);
    }

    /**
     * Create a <code>rules.default_2024_race</code> table reference
     */
    public Default_2024Race() {
        this(DSL.name("default_2024_race"), null);
    }

    public <O extends Record> Default_2024Race(Table<O> path, ForeignKey<O, Default_2024RaceRecord> childPath, InverseForeignKey<O, Default_2024RaceRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_2024_RACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_2024RacePath extends Default_2024Race implements Path<Default_2024RaceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_2024RacePath(Table<O> path, ForeignKey<O, Default_2024RaceRecord> childPath, InverseForeignKey<O, Default_2024RaceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_2024RacePath(Name alias, Table<Default_2024RaceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_2024RacePath as(String alias) {
            return new Default_2024RacePath(DSL.name(alias), this);
        }

        @Override
        public Default_2024RacePath as(Name alias) {
            return new Default_2024RacePath(alias, this);
        }

        @Override
        public Default_2024RacePath as(Table<?> alias) {
            return new Default_2024RacePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_2024RaceRecord> getPrimaryKey() {
        return Keys.DEFAULT_2024_RACE_PKEY;
    }

    @Override
    public List<ForeignKey<Default_2024RaceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_2024_RACE__FKDEFAULT_2024_RACE_STATS);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.DEFAULT_2024_RACE__FKDEFAULT_2024_RACE_STATS, null);

        return _raceStats;
    }

    @Override
    public Default_2024Race as(String alias) {
        return new Default_2024Race(DSL.name(alias), this);
    }

    @Override
    public Default_2024Race as(Name alias) {
        return new Default_2024Race(alias, this);
    }

    @Override
    public Default_2024Race as(Table<?> alias) {
        return new Default_2024Race(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Race rename(String name) {
        return new Default_2024Race(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Race rename(Name name) {
        return new Default_2024Race(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Race rename(Table<?> name) {
        return new Default_2024Race(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race where(Condition condition) {
        return new Default_2024Race(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Race where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Race where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Race where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Race where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Race whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
