/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.ClazzStats.ClazzStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_2024ClazzRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_2024Clazz extends TableImpl<Default_2024ClazzRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_2024_clazz</code>
     */
    public static final Default_2024Clazz DEFAULT_2024_CLAZZ = new Default_2024Clazz();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_2024ClazzRecord> getRecordType() {
        return Default_2024ClazzRecord.class;
    }

    /**
     * The column <code>rules.default_2024_clazz.id</code>.
     */
    public final TableField<Default_2024ClazzRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_clazz.name</code>.
     */
    public final TableField<Default_2024ClazzRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_clazz.description</code>.
     */
    public final TableField<Default_2024ClazzRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_2024_clazz.code</code>.
     */
    public final TableField<Default_2024ClazzRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_clazz.clazz_stats_id</code>.
     */
    public final TableField<Default_2024ClazzRecord, UUID> CLAZZ_STATS_ID = createField(DSL.name("clazz_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_clazz.img_url</code>.
     */
    public final TableField<Default_2024ClazzRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.default_2024_clazz.group_code</code>.
     */
    public final TableField<Default_2024ClazzRecord, String> GROUP_CODE = createField(DSL.name("group_code"), SQLDataType.VARCHAR, this, "");

    private Default_2024Clazz(Name alias, Table<Default_2024ClazzRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_2024Clazz(Name alias, Table<Default_2024ClazzRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_2024_clazz</code> table reference
     */
    public Default_2024Clazz(String alias) {
        this(DSL.name(alias), DEFAULT_2024_CLAZZ);
    }

    /**
     * Create an aliased <code>rules.default_2024_clazz</code> table reference
     */
    public Default_2024Clazz(Name alias) {
        this(alias, DEFAULT_2024_CLAZZ);
    }

    /**
     * Create a <code>rules.default_2024_clazz</code> table reference
     */
    public Default_2024Clazz() {
        this(DSL.name("default_2024_clazz"), null);
    }

    public <O extends Record> Default_2024Clazz(Table<O> path, ForeignKey<O, Default_2024ClazzRecord> childPath, InverseForeignKey<O, Default_2024ClazzRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_2024_CLAZZ);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_2024ClazzPath extends Default_2024Clazz implements Path<Default_2024ClazzRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_2024ClazzPath(Table<O> path, ForeignKey<O, Default_2024ClazzRecord> childPath, InverseForeignKey<O, Default_2024ClazzRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_2024ClazzPath(Name alias, Table<Default_2024ClazzRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_2024ClazzPath as(String alias) {
            return new Default_2024ClazzPath(DSL.name(alias), this);
        }

        @Override
        public Default_2024ClazzPath as(Name alias) {
            return new Default_2024ClazzPath(alias, this);
        }

        @Override
        public Default_2024ClazzPath as(Table<?> alias) {
            return new Default_2024ClazzPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_2024ClazzRecord> getPrimaryKey() {
        return Keys.DEFAULT_2024_CLAZZ_PKEY;
    }

    @Override
    public List<ForeignKey<Default_2024ClazzRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_2024_CLAZZ__FKDEFAULT_2024_CLAZZ_STATS);
    }

    private transient ClazzStatsPath _clazzStats;

    /**
     * Get the implicit join path to the <code>rules.clazz_stats</code> table.
     */
    public ClazzStatsPath clazzStats() {
        if (_clazzStats == null)
            _clazzStats = new ClazzStatsPath(this, Keys.DEFAULT_2024_CLAZZ__FKDEFAULT_2024_CLAZZ_STATS, null);

        return _clazzStats;
    }

    @Override
    public Default_2024Clazz as(String alias) {
        return new Default_2024Clazz(DSL.name(alias), this);
    }

    @Override
    public Default_2024Clazz as(Name alias) {
        return new Default_2024Clazz(alias, this);
    }

    @Override
    public Default_2024Clazz as(Table<?> alias) {
        return new Default_2024Clazz(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Clazz rename(String name) {
        return new Default_2024Clazz(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Clazz rename(Name name) {
        return new Default_2024Clazz(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Clazz rename(Table<?> name) {
        return new Default_2024Clazz(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz where(Condition condition) {
        return new Default_2024Clazz(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Clazz where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Clazz where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Clazz where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Clazz where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Clazz whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
