/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundStats.BackgroundStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.DefaultEberronBackgroundRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Предыстории по умолчанию для сеттинга Eberron (Eberron: Rising from the Last
 * War)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultEberronBackground extends TableImpl<DefaultEberronBackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_eberron_background</code>
     */
    public static final DefaultEberronBackground DEFAULT_EBERRON_BACKGROUND = new DefaultEberronBackground();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DefaultEberronBackgroundRecord> getRecordType() {
        return DefaultEberronBackgroundRecord.class;
    }

    /**
     * The column <code>rules.default_eberron_background.id</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_eberron_background.name</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_eberron_background.description</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_eberron_background.code</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_eberron_background.img_url</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column
     * <code>rules.default_eberron_background.background_stats_id</code>.
     */
    public final TableField<DefaultEberronBackgroundRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private DefaultEberronBackground(Name alias, Table<DefaultEberronBackgroundRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DefaultEberronBackground(Name alias, Table<DefaultEberronBackgroundRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Предыстории по умолчанию для сеттинга Eberron (Eberron: Rising from the Last War)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_eberron_background</code> table
     * reference
     */
    public DefaultEberronBackground(String alias) {
        this(DSL.name(alias), DEFAULT_EBERRON_BACKGROUND);
    }

    /**
     * Create an aliased <code>rules.default_eberron_background</code> table
     * reference
     */
    public DefaultEberronBackground(Name alias) {
        this(alias, DEFAULT_EBERRON_BACKGROUND);
    }

    /**
     * Create a <code>rules.default_eberron_background</code> table reference
     */
    public DefaultEberronBackground() {
        this(DSL.name("default_eberron_background"), null);
    }

    public <O extends Record> DefaultEberronBackground(Table<O> path, ForeignKey<O, DefaultEberronBackgroundRecord> childPath, InverseForeignKey<O, DefaultEberronBackgroundRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_EBERRON_BACKGROUND);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DefaultEberronBackgroundPath extends DefaultEberronBackground implements Path<DefaultEberronBackgroundRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DefaultEberronBackgroundPath(Table<O> path, ForeignKey<O, DefaultEberronBackgroundRecord> childPath, InverseForeignKey<O, DefaultEberronBackgroundRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DefaultEberronBackgroundPath(Name alias, Table<DefaultEberronBackgroundRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DefaultEberronBackgroundPath as(String alias) {
            return new DefaultEberronBackgroundPath(DSL.name(alias), this);
        }

        @Override
        public DefaultEberronBackgroundPath as(Name alias) {
            return new DefaultEberronBackgroundPath(alias, this);
        }

        @Override
        public DefaultEberronBackgroundPath as(Table<?> alias) {
            return new DefaultEberronBackgroundPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<DefaultEberronBackgroundRecord> getPrimaryKey() {
        return Keys.DEFAULT_EBERRON_BACKGROUND_PKEY;
    }

    @Override
    public List<ForeignKey<DefaultEberronBackgroundRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_EBERRON_BACKGROUND__FK_DEFAULT_EBERRON_BACKGROUND_STATS);
    }

    private transient BackgroundStatsPath _backgroundStats;

    /**
     * Get the implicit join path to the <code>rules.background_stats</code>
     * table.
     */
    public BackgroundStatsPath backgroundStats() {
        if (_backgroundStats == null)
            _backgroundStats = new BackgroundStatsPath(this, Keys.DEFAULT_EBERRON_BACKGROUND__FK_DEFAULT_EBERRON_BACKGROUND_STATS, null);

        return _backgroundStats;
    }

    @Override
    public DefaultEberronBackground as(String alias) {
        return new DefaultEberronBackground(DSL.name(alias), this);
    }

    @Override
    public DefaultEberronBackground as(Name alias) {
        return new DefaultEberronBackground(alias, this);
    }

    @Override
    public DefaultEberronBackground as(Table<?> alias) {
        return new DefaultEberronBackground(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultEberronBackground rename(String name) {
        return new DefaultEberronBackground(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultEberronBackground rename(Name name) {
        return new DefaultEberronBackground(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefaultEberronBackground rename(Table<?> name) {
        return new DefaultEberronBackground(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground where(Condition condition) {
        return new DefaultEberronBackground(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultEberronBackground where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultEberronBackground where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultEberronBackground where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DefaultEberronBackground where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DefaultEberronBackground whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
