/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.ClazzStats.ClazzStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eClazzRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eClazz extends TableImpl<Default_5eClazzRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_5e_clazz</code>
     */
    public static final Default_5eClazz DEFAULT_5E_CLAZZ = new Default_5eClazz();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_5eClazzRecord> getRecordType() {
        return Default_5eClazzRecord.class;
    }

    /**
     * The column <code>rules.default_5e_clazz.id</code>.
     */
    public final TableField<Default_5eClazzRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_clazz.name</code>.
     */
    public final TableField<Default_5eClazzRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_clazz.description</code>.
     */
    public final TableField<Default_5eClazzRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_5e_clazz.code</code>.
     */
    public final TableField<Default_5eClazzRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_clazz.clazz_stats_id</code>.
     */
    public final TableField<Default_5eClazzRecord, UUID> CLAZZ_STATS_ID = createField(DSL.name("clazz_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_5e_clazz.img_url</code>.
     */
    public final TableField<Default_5eClazzRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.default_5e_clazz.group_code</code>.
     */
    public final TableField<Default_5eClazzRecord, String> GROUP_CODE = createField(DSL.name("group_code"), SQLDataType.VARCHAR, this, "");

    private Default_5eClazz(Name alias, Table<Default_5eClazzRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_5eClazz(Name alias, Table<Default_5eClazzRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_5e_clazz</code> table reference
     */
    public Default_5eClazz(String alias) {
        this(DSL.name(alias), DEFAULT_5E_CLAZZ);
    }

    /**
     * Create an aliased <code>rules.default_5e_clazz</code> table reference
     */
    public Default_5eClazz(Name alias) {
        this(alias, DEFAULT_5E_CLAZZ);
    }

    /**
     * Create a <code>rules.default_5e_clazz</code> table reference
     */
    public Default_5eClazz() {
        this(DSL.name("default_5e_clazz"), null);
    }

    public <O extends Record> Default_5eClazz(Table<O> path, ForeignKey<O, Default_5eClazzRecord> childPath, InverseForeignKey<O, Default_5eClazzRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_5E_CLAZZ);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_5eClazzPath extends Default_5eClazz implements Path<Default_5eClazzRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_5eClazzPath(Table<O> path, ForeignKey<O, Default_5eClazzRecord> childPath, InverseForeignKey<O, Default_5eClazzRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_5eClazzPath(Name alias, Table<Default_5eClazzRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_5eClazzPath as(String alias) {
            return new Default_5eClazzPath(DSL.name(alias), this);
        }

        @Override
        public Default_5eClazzPath as(Name alias) {
            return new Default_5eClazzPath(alias, this);
        }

        @Override
        public Default_5eClazzPath as(Table<?> alias) {
            return new Default_5eClazzPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_5eClazzRecord> getPrimaryKey() {
        return Keys.DEFAULT_5E_CLAZZ_PKEY;
    }

    @Override
    public List<ForeignKey<Default_5eClazzRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_5E_CLAZZ__FKDEFAULT_5E174476);
    }

    private transient ClazzStatsPath _clazzStats;

    /**
     * Get the implicit join path to the <code>rules.clazz_stats</code> table.
     */
    public ClazzStatsPath clazzStats() {
        if (_clazzStats == null)
            _clazzStats = new ClazzStatsPath(this, Keys.DEFAULT_5E_CLAZZ__FKDEFAULT_5E174476, null);

        return _clazzStats;
    }

    @Override
    public Default_5eClazz as(String alias) {
        return new Default_5eClazz(DSL.name(alias), this);
    }

    @Override
    public Default_5eClazz as(Name alias) {
        return new Default_5eClazz(alias, this);
    }

    @Override
    public Default_5eClazz as(Table<?> alias) {
        return new Default_5eClazz(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClazz rename(String name) {
        return new Default_5eClazz(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClazz rename(Name name) {
        return new Default_5eClazz(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_5eClazz rename(Table<?> name) {
        return new Default_5eClazz(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz where(Condition condition) {
        return new Default_5eClazz(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClazz where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClazz where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClazz where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_5eClazz where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_5eClazz whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
