/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundStats.BackgroundStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_2024BackgroundRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Предыстории по умолчанию для D&amp;D 2024 (PHB)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_2024Background extends TableImpl<Default_2024BackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.default_2024_background</code>
     */
    public static final Default_2024Background DEFAULT_2024_BACKGROUND = new Default_2024Background();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Default_2024BackgroundRecord> getRecordType() {
        return Default_2024BackgroundRecord.class;
    }

    /**
     * The column <code>rules.default_2024_background.id</code>.
     */
    public final TableField<Default_2024BackgroundRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_background.name</code>.
     */
    public final TableField<Default_2024BackgroundRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_background.description</code>.
     */
    public final TableField<Default_2024BackgroundRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.default_2024_background.code</code>.
     */
    public final TableField<Default_2024BackgroundRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.default_2024_background.img_url</code>.
     */
    public final TableField<Default_2024BackgroundRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column
     * <code>rules.default_2024_background.background_stats_id</code>.
     */
    public final TableField<Default_2024BackgroundRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Default_2024Background(Name alias, Table<Default_2024BackgroundRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Default_2024Background(Name alias, Table<Default_2024BackgroundRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Предыстории по умолчанию для D&D 2024 (PHB)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.default_2024_background</code> table
     * reference
     */
    public Default_2024Background(String alias) {
        this(DSL.name(alias), DEFAULT_2024_BACKGROUND);
    }

    /**
     * Create an aliased <code>rules.default_2024_background</code> table
     * reference
     */
    public Default_2024Background(Name alias) {
        this(alias, DEFAULT_2024_BACKGROUND);
    }

    /**
     * Create a <code>rules.default_2024_background</code> table reference
     */
    public Default_2024Background() {
        this(DSL.name("default_2024_background"), null);
    }

    public <O extends Record> Default_2024Background(Table<O> path, ForeignKey<O, Default_2024BackgroundRecord> childPath, InverseForeignKey<O, Default_2024BackgroundRecord> parentPath) {
        super(path, childPath, parentPath, DEFAULT_2024_BACKGROUND);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class Default_2024BackgroundPath extends Default_2024Background implements Path<Default_2024BackgroundRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> Default_2024BackgroundPath(Table<O> path, ForeignKey<O, Default_2024BackgroundRecord> childPath, InverseForeignKey<O, Default_2024BackgroundRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private Default_2024BackgroundPath(Name alias, Table<Default_2024BackgroundRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public Default_2024BackgroundPath as(String alias) {
            return new Default_2024BackgroundPath(DSL.name(alias), this);
        }

        @Override
        public Default_2024BackgroundPath as(Name alias) {
            return new Default_2024BackgroundPath(alias, this);
        }

        @Override
        public Default_2024BackgroundPath as(Table<?> alias) {
            return new Default_2024BackgroundPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Default_2024BackgroundRecord> getPrimaryKey() {
        return Keys.DEFAULT_2024_BACKGROUND_PKEY;
    }

    @Override
    public List<ForeignKey<Default_2024BackgroundRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DEFAULT_2024_BACKGROUND__FK_DEFAULT_2024_BACKGROUND_STATS);
    }

    private transient BackgroundStatsPath _backgroundStats;

    /**
     * Get the implicit join path to the <code>rules.background_stats</code>
     * table.
     */
    public BackgroundStatsPath backgroundStats() {
        if (_backgroundStats == null)
            _backgroundStats = new BackgroundStatsPath(this, Keys.DEFAULT_2024_BACKGROUND__FK_DEFAULT_2024_BACKGROUND_STATS, null);

        return _backgroundStats;
    }

    @Override
    public Default_2024Background as(String alias) {
        return new Default_2024Background(DSL.name(alias), this);
    }

    @Override
    public Default_2024Background as(Name alias) {
        return new Default_2024Background(alias, this);
    }

    @Override
    public Default_2024Background as(Table<?> alias) {
        return new Default_2024Background(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Background rename(String name) {
        return new Default_2024Background(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Background rename(Name name) {
        return new Default_2024Background(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Default_2024Background rename(Table<?> name) {
        return new Default_2024Background(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background where(Condition condition) {
        return new Default_2024Background(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Background where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Background where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Background where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Default_2024Background where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Default_2024Background whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
