/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Room.RoomPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Race extends TableImpl<RaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.race</code>
     */
    public static final Race RACE = new Race();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceRecord> getRecordType() {
        return RaceRecord.class;
    }

    /**
     * The column <code>rules.race.id</code>.
     */
    public final TableField<RaceRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race.room_id</code>.
     */
    public final TableField<RaceRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>rules.race.name</code>.
     */
    public final TableField<RaceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race.description</code>.
     */
    public final TableField<RaceRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.race.code</code>.
     */
    public final TableField<RaceRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race.race_stats_id</code>.
     */
    public final TableField<RaceRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race.img_url</code>.
     */
    public final TableField<RaceRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.race.species_code</code>.
     */
    public final TableField<RaceRecord, String> SPECIES_CODE = createField(DSL.name("species_code"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.race.hidden</code>.
     */
    public final TableField<RaceRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>rules.race.bundle_id</code>.
     */
    public final TableField<RaceRecord, UUID> BUNDLE_ID = createField(DSL.name("bundle_id"), SQLDataType.UUID, this, "");

    private Race(Name alias, Table<RaceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Race(Name alias, Table<RaceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.race</code> table reference
     */
    public Race(String alias) {
        this(DSL.name(alias), RACE);
    }

    /**
     * Create an aliased <code>rules.race</code> table reference
     */
    public Race(Name alias) {
        this(alias, RACE);
    }

    /**
     * Create a <code>rules.race</code> table reference
     */
    public Race() {
        this(DSL.name("race"), null);
    }

    public <O extends Record> Race(Table<O> path, ForeignKey<O, RaceRecord> childPath, InverseForeignKey<O, RaceRecord> parentPath) {
        super(path, childPath, parentPath, RACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RacePath extends Race implements Path<RaceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RacePath(Table<O> path, ForeignKey<O, RaceRecord> childPath, InverseForeignKey<O, RaceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RacePath(Name alias, Table<RaceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RacePath as(String alias) {
            return new RacePath(DSL.name(alias), this);
        }

        @Override
        public RacePath as(Name alias) {
            return new RacePath(alias, this);
        }

        @Override
        public RacePath as(Table<?> alias) {
            return new RacePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RACE_BUNDLE_ID_IDX, Indexes.RACE_ROOM_ID);
    }

    @Override
    public UniqueKey<RaceRecord> getPrimaryKey() {
        return Keys.RACE_PKEY;
    }

    @Override
    public List<ForeignKey<RaceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RACE__FKRACE214766, Keys.RACE__FKRACE292535);
    }

    private transient RoomPath _room;

    /**
     * Get the implicit join path to the <code>rules.room</code> table.
     */
    public RoomPath room() {
        if (_room == null)
            _room = new RoomPath(this, Keys.RACE__FKRACE214766, null);

        return _room;
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.RACE__FKRACE292535, null);

        return _raceStats;
    }

    @Override
    public Race as(String alias) {
        return new Race(DSL.name(alias), this);
    }

    @Override
    public Race as(Name alias) {
        return new Race(alias, this);
    }

    @Override
    public Race as(Table<?> alias) {
        return new Race(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Race rename(String name) {
        return new Race(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Race rename(Name name) {
        return new Race(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Race rename(Table<?> name) {
        return new Race(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race where(Condition condition) {
        return new Race(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Race where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Race where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Race where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Race where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Race whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
