/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceTraitsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceTraits extends TableImpl<RaceTraitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.race_traits</code>
     */
    public static final RaceTraits RACE_TRAITS = new RaceTraits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceTraitsRecord> getRecordType() {
        return RaceTraitsRecord.class;
    }

    /**
     * The column <code>rules.race_traits.id</code>.
     */
    public final TableField<RaceTraitsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_traits.race_stats_id</code>.
     */
    public final TableField<RaceTraitsRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_traits.name</code>.
     */
    public final TableField<RaceTraitsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race_traits.code</code>.
     */
    public final TableField<RaceTraitsRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race_traits.description</code>.
     */
    public final TableField<RaceTraitsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private RaceTraits(Name alias, Table<RaceTraitsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RaceTraits(Name alias, Table<RaceTraitsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.race_traits</code> table reference
     */
    public RaceTraits(String alias) {
        this(DSL.name(alias), RACE_TRAITS);
    }

    /**
     * Create an aliased <code>rules.race_traits</code> table reference
     */
    public RaceTraits(Name alias) {
        this(alias, RACE_TRAITS);
    }

    /**
     * Create a <code>rules.race_traits</code> table reference
     */
    public RaceTraits() {
        this(DSL.name("race_traits"), null);
    }

    public <O extends Record> RaceTraits(Table<O> path, ForeignKey<O, RaceTraitsRecord> childPath, InverseForeignKey<O, RaceTraitsRecord> parentPath) {
        super(path, childPath, parentPath, RACE_TRAITS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RaceTraitsPath extends RaceTraits implements Path<RaceTraitsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RaceTraitsPath(Table<O> path, ForeignKey<O, RaceTraitsRecord> childPath, InverseForeignKey<O, RaceTraitsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RaceTraitsPath(Name alias, Table<RaceTraitsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RaceTraitsPath as(String alias) {
            return new RaceTraitsPath(DSL.name(alias), this);
        }

        @Override
        public RaceTraitsPath as(Name alias) {
            return new RaceTraitsPath(alias, this);
        }

        @Override
        public RaceTraitsPath as(Table<?> alias) {
            return new RaceTraitsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<RaceTraitsRecord> getPrimaryKey() {
        return Keys.RACE_TRAITS_PKEY;
    }

    @Override
    public List<ForeignKey<RaceTraitsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RACE_TRAITS__FKRACE_TRAIT331219);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.RACE_TRAITS__FKRACE_TRAIT331219, null);

        return _raceStats;
    }

    @Override
    public RaceTraits as(String alias) {
        return new RaceTraits(DSL.name(alias), this);
    }

    @Override
    public RaceTraits as(Name alias) {
        return new RaceTraits(alias, this);
    }

    @Override
    public RaceTraits as(Table<?> alias) {
        return new RaceTraits(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTraits rename(String name) {
        return new RaceTraits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTraits rename(Name name) {
        return new RaceTraits(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTraits rename(Table<?> name) {
        return new RaceTraits(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits where(Condition condition) {
        return new RaceTraits(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTraits where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTraits where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTraits where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTraits where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTraits whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
