/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRaces.Default_5eRacesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies.RaceProficienciesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits.RaceTraitsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Races.RacesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceStatsRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceStats extends TableImpl<RaceStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.race_stats</code>
     */
    public static final RaceStats RACE_STATS = new RaceStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceStatsRecord> getRecordType() {
        return RaceStatsRecord.class;
    }

    /**
     * The column <code>rules.race_stats.id</code>.
     */
    public final TableField<RaceStatsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_stats.max_age</code>.
     */
    public final TableField<RaceStatsRecord, Integer> MAX_AGE = createField(DSL.name("max_age"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.race_stats.max_height</code>.
     */
    public final TableField<RaceStatsRecord, Integer> MAX_HEIGHT = createField(DSL.name("max_height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.race_stats.max_weight</code>.
     */
    public final TableField<RaceStatsRecord, Integer> MAX_WEIGHT = createField(DSL.name("max_weight"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.race_stats.base_speed</code>.
     */
    public final TableField<RaceStatsRecord, Integer> BASE_SPEED = createField(DSL.name("base_speed"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.race_stats.ability_modifiers</code>.
     */
    public final TableField<RaceStatsRecord, JSONB> ABILITY_MODIFIERS = createField(DSL.name("ability_modifiers"), SQLDataType.JSONB.nullable(false), this, "");

    private RaceStats(Name alias, Table<RaceStatsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RaceStats(Name alias, Table<RaceStatsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.race_stats</code> table reference
     */
    public RaceStats(String alias) {
        this(DSL.name(alias), RACE_STATS);
    }

    /**
     * Create an aliased <code>rules.race_stats</code> table reference
     */
    public RaceStats(Name alias) {
        this(alias, RACE_STATS);
    }

    /**
     * Create a <code>rules.race_stats</code> table reference
     */
    public RaceStats() {
        this(DSL.name("race_stats"), null);
    }

    public <O extends Record> RaceStats(Table<O> path, ForeignKey<O, RaceStatsRecord> childPath, InverseForeignKey<O, RaceStatsRecord> parentPath) {
        super(path, childPath, parentPath, RACE_STATS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RaceStatsPath extends RaceStats implements Path<RaceStatsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RaceStatsPath(Table<O> path, ForeignKey<O, RaceStatsRecord> childPath, InverseForeignKey<O, RaceStatsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RaceStatsPath(Name alias, Table<RaceStatsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RaceStatsPath as(String alias) {
            return new RaceStatsPath(DSL.name(alias), this);
        }

        @Override
        public RaceStatsPath as(Name alias) {
            return new RaceStatsPath(alias, this);
        }

        @Override
        public RaceStatsPath as(Table<?> alias) {
            return new RaceStatsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<RaceStatsRecord> getPrimaryKey() {
        return Keys.RACE_STATS_PKEY;
    }

    private transient Default_5eRacesPath _default_5eRaces;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.default_5e_races</code> table
     */
    public Default_5eRacesPath default_5eRaces() {
        if (_default_5eRaces == null)
            _default_5eRaces = new Default_5eRacesPath(this, null, Keys.DEFAULT_5E_RACES__FKDEFAULT_5E40267.getInverseKey());

        return _default_5eRaces;
    }

    private transient RaceProficienciesPath _raceProficiencies;

    /**
     * Get the implicit to-many join path to the
     * <code>rules.race_proficiencies</code> table
     */
    public RaceProficienciesPath raceProficiencies() {
        if (_raceProficiencies == null)
            _raceProficiencies = new RaceProficienciesPath(this, null, Keys.RACE_PROFICIENCIES__FKRACE_PROFI169598.getInverseKey());

        return _raceProficiencies;
    }

    private transient RaceTraitsPath _raceTraits;

    /**
     * Get the implicit to-many join path to the <code>rules.race_traits</code>
     * table
     */
    public RaceTraitsPath raceTraits() {
        if (_raceTraits == null)
            _raceTraits = new RaceTraitsPath(this, null, Keys.RACE_TRAITS__FKRACE_TRAIT331219.getInverseKey());

        return _raceTraits;
    }

    private transient RacesPath _races;

    /**
     * Get the implicit to-many join path to the <code>rules.races</code> table
     */
    public RacesPath races() {
        if (_races == null)
            _races = new RacesPath(this, null, Keys.RACES__FKRACES292535.getInverseKey());

        return _races;
    }

    @Override
    public RaceStats as(String alias) {
        return new RaceStats(DSL.name(alias), this);
    }

    @Override
    public RaceStats as(Name alias) {
        return new RaceStats(alias, this);
    }

    @Override
    public RaceStats as(Table<?> alias) {
        return new RaceStats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceStats rename(String name) {
        return new RaceStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceStats rename(Name name) {
        return new RaceStats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceStats rename(Table<?> name) {
        return new RaceStats(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats where(Condition condition) {
        return new RaceStats(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceStats where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceStats where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceStats where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceStats where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceStats whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
