/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceTraitRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceTrait extends TableImpl<RaceTraitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.race_trait</code>
     */
    public static final RaceTrait RACE_TRAIT = new RaceTrait();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceTraitRecord> getRecordType() {
        return RaceTraitRecord.class;
    }

    /**
     * The column <code>rules.race_trait.id</code>.
     */
    public final TableField<RaceTraitRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_trait.race_stats_id</code>.
     */
    public final TableField<RaceTraitRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_trait.name</code>.
     */
    public final TableField<RaceTraitRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race_trait.code</code>.
     */
    public final TableField<RaceTraitRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race_trait.description</code>.
     */
    public final TableField<RaceTraitRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private RaceTrait(Name alias, Table<RaceTraitRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RaceTrait(Name alias, Table<RaceTraitRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.race_trait</code> table reference
     */
    public RaceTrait(String alias) {
        this(DSL.name(alias), RACE_TRAIT);
    }

    /**
     * Create an aliased <code>rules.race_trait</code> table reference
     */
    public RaceTrait(Name alias) {
        this(alias, RACE_TRAIT);
    }

    /**
     * Create a <code>rules.race_trait</code> table reference
     */
    public RaceTrait() {
        this(DSL.name("race_trait"), null);
    }

    public <O extends Record> RaceTrait(Table<O> path, ForeignKey<O, RaceTraitRecord> childPath, InverseForeignKey<O, RaceTraitRecord> parentPath) {
        super(path, childPath, parentPath, RACE_TRAIT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RaceTraitPath extends RaceTrait implements Path<RaceTraitRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RaceTraitPath(Table<O> path, ForeignKey<O, RaceTraitRecord> childPath, InverseForeignKey<O, RaceTraitRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RaceTraitPath(Name alias, Table<RaceTraitRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RaceTraitPath as(String alias) {
            return new RaceTraitPath(DSL.name(alias), this);
        }

        @Override
        public RaceTraitPath as(Name alias) {
            return new RaceTraitPath(alias, this);
        }

        @Override
        public RaceTraitPath as(Table<?> alias) {
            return new RaceTraitPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RACE_TRAIT_RACE_STATS_ID);
    }

    @Override
    public UniqueKey<RaceTraitRecord> getPrimaryKey() {
        return Keys.RACE_TRAIT_PKEY;
    }

    @Override
    public List<ForeignKey<RaceTraitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RACE_TRAIT__FKRACE_TRAIT331219);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.RACE_TRAIT__FKRACE_TRAIT331219, null);

        return _raceStats;
    }

    @Override
    public RaceTrait as(String alias) {
        return new RaceTrait(DSL.name(alias), this);
    }

    @Override
    public RaceTrait as(Name alias) {
        return new RaceTrait(alias, this);
    }

    @Override
    public RaceTrait as(Table<?> alias) {
        return new RaceTrait(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTrait rename(String name) {
        return new RaceTrait(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTrait rename(Name name) {
        return new RaceTrait(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceTrait rename(Table<?> name) {
        return new RaceTrait(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait where(Condition condition) {
        return new RaceTrait(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTrait where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTrait where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTrait where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceTrait where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceTrait whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
