/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats.RaceStatsPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceProficiencyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceProficiency extends TableImpl<RaceProficiencyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.race_proficiency</code>
     */
    public static final RaceProficiency RACE_PROFICIENCY = new RaceProficiency();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RaceProficiencyRecord> getRecordType() {
        return RaceProficiencyRecord.class;
    }

    /**
     * The column <code>rules.race_proficiency.id</code>.
     */
    public final TableField<RaceProficiencyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_proficiency.race_stats_id</code>.
     */
    public final TableField<RaceProficiencyRecord, UUID> RACE_STATS_ID = createField(DSL.name("race_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.race_proficiency.type</code>.
     */
    public final TableField<RaceProficiencyRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.race_proficiency.code</code>.
     */
    public final TableField<RaceProficiencyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    private RaceProficiency(Name alias, Table<RaceProficiencyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RaceProficiency(Name alias, Table<RaceProficiencyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.race_proficiency</code> table reference
     */
    public RaceProficiency(String alias) {
        this(DSL.name(alias), RACE_PROFICIENCY);
    }

    /**
     * Create an aliased <code>rules.race_proficiency</code> table reference
     */
    public RaceProficiency(Name alias) {
        this(alias, RACE_PROFICIENCY);
    }

    /**
     * Create a <code>rules.race_proficiency</code> table reference
     */
    public RaceProficiency() {
        this(DSL.name("race_proficiency"), null);
    }

    public <O extends Record> RaceProficiency(Table<O> path, ForeignKey<O, RaceProficiencyRecord> childPath, InverseForeignKey<O, RaceProficiencyRecord> parentPath) {
        super(path, childPath, parentPath, RACE_PROFICIENCY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RaceProficiencyPath extends RaceProficiency implements Path<RaceProficiencyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RaceProficiencyPath(Table<O> path, ForeignKey<O, RaceProficiencyRecord> childPath, InverseForeignKey<O, RaceProficiencyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RaceProficiencyPath(Name alias, Table<RaceProficiencyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RaceProficiencyPath as(String alias) {
            return new RaceProficiencyPath(DSL.name(alias), this);
        }

        @Override
        public RaceProficiencyPath as(Name alias) {
            return new RaceProficiencyPath(alias, this);
        }

        @Override
        public RaceProficiencyPath as(Table<?> alias) {
            return new RaceProficiencyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.RACE_PROFICIENCY_RACE_STATS_ID);
    }

    @Override
    public UniqueKey<RaceProficiencyRecord> getPrimaryKey() {
        return Keys.RACE_PROFICIENCY_PKEY;
    }

    @Override
    public List<ForeignKey<RaceProficiencyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RACE_PROFICIENCY__FKRACE_PROFI169598);
    }

    private transient RaceStatsPath _raceStats;

    /**
     * Get the implicit join path to the <code>rules.race_stats</code> table.
     */
    public RaceStatsPath raceStats() {
        if (_raceStats == null)
            _raceStats = new RaceStatsPath(this, Keys.RACE_PROFICIENCY__FKRACE_PROFI169598, null);

        return _raceStats;
    }

    @Override
    public RaceProficiency as(String alias) {
        return new RaceProficiency(DSL.name(alias), this);
    }

    @Override
    public RaceProficiency as(Name alias) {
        return new RaceProficiency(alias, this);
    }

    @Override
    public RaceProficiency as(Table<?> alias) {
        return new RaceProficiency(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceProficiency rename(String name) {
        return new RaceProficiency(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceProficiency rename(Name name) {
        return new RaceProficiency(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RaceProficiency rename(Table<?> name) {
        return new RaceProficiency(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency where(Condition condition) {
        return new RaceProficiency(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceProficiency where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceProficiency where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceProficiency where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RaceProficiency where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RaceProficiency whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
