/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Ability.AbilityPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Clazz.ClazzPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Race.RacePath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RoomRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Реплика информации о комнате из core микросервиса
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Room extends TableImpl<RoomRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.room</code>
     */
    public static final Room ROOM = new Room();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRecord> getRecordType() {
        return RoomRecord.class;
    }

    /**
     * The column <code>rules.room.room_id</code>.
     */
    public final TableField<RoomRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.room.owner_id</code>. Id владельца комнаты
     */
    public final TableField<RoomRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "Id владельца комнаты");

    /**
     * The column <code>rules.room.rule_type</code>. Тип правил, например: 4e,
     * 5e, homebrew
     */
    public final TableField<RoomRecord, String> RULE_TYPE = createField(DSL.name("rule_type"), SQLDataType.CLOB.nullable(false), this, "Тип правил, например: 4e, 5e, homebrew");

    /**
     * The column <code>rules.room.base_rule_type</code>.
     */
    public final TableField<RoomRecord, String> BASE_RULE_TYPE = createField(DSL.name("base_rule_type"), SQLDataType.CLOB, this, "");

    private Room(Name alias, Table<RoomRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Room(Name alias, Table<RoomRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Реплика информации о комнате из core микросервиса"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.room</code> table reference
     */
    public Room(String alias) {
        this(DSL.name(alias), ROOM);
    }

    /**
     * Create an aliased <code>rules.room</code> table reference
     */
    public Room(Name alias) {
        this(alias, ROOM);
    }

    /**
     * Create a <code>rules.room</code> table reference
     */
    public Room() {
        this(DSL.name("room"), null);
    }

    public <O extends Record> Room(Table<O> path, ForeignKey<O, RoomRecord> childPath, InverseForeignKey<O, RoomRecord> parentPath) {
        super(path, childPath, parentPath, ROOM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoomPath extends Room implements Path<RoomRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoomPath(Table<O> path, ForeignKey<O, RoomRecord> childPath, InverseForeignKey<O, RoomRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoomPath(Name alias, Table<RoomRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoomPath as(String alias) {
            return new RoomPath(DSL.name(alias), this);
        }

        @Override
        public RoomPath as(Name alias) {
            return new RoomPath(alias, this);
        }

        @Override
        public RoomPath as(Table<?> alias) {
            return new RoomPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<RoomRecord> getPrimaryKey() {
        return Keys.ROOM_PKEY;
    }

    private transient AbilityPath _ability;

    /**
     * Get the implicit to-many join path to the <code>rules.ability</code>
     * table
     */
    public AbilityPath ability() {
        if (_ability == null)
            _ability = new AbilityPath(this, null, Keys.ABILITY__FKABILITY898405.getInverseKey());

        return _ability;
    }

    private transient ClazzPath _clazz;

    /**
     * Get the implicit to-many join path to the <code>rules.clazz</code> table
     */
    public ClazzPath clazz() {
        if (_clazz == null)
            _clazz = new ClazzPath(this, null, Keys.CLAZZ__FKCLAZZ862752.getInverseKey());

        return _clazz;
    }

    private transient RacePath _race;

    /**
     * Get the implicit to-many join path to the <code>rules.race</code> table
     */
    public RacePath race() {
        if (_race == null)
            _race = new RacePath(this, null, Keys.RACE__FKRACE214766.getInverseKey());

        return _race;
    }

    @Override
    public Room as(String alias) {
        return new Room(DSL.name(alias), this);
    }

    @Override
    public Room as(Name alias) {
        return new Room(alias, this);
    }

    @Override
    public Room as(Table<?> alias) {
        return new Room(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(String name) {
        return new Room(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(Name name) {
        return new Room(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Room rename(Table<?> name) {
        return new Room(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room where(Condition condition) {
        return new Room(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Room where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Room where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Room where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Room where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Room whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
