/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Abilities.AbilitiesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes.ClassesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.Races.RacesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RoomsRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Реплика информации о комнате из core микросервиса
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rooms extends TableImpl<RoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.rooms</code>
     */
    public static final Rooms ROOMS = new Rooms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomsRecord> getRecordType() {
        return RoomsRecord.class;
    }

    /**
     * The column <code>rules.rooms.room_id</code>.
     */
    public final TableField<RoomsRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.rooms.owner_id</code>. Id владельца комнаты
     */
    public final TableField<RoomsRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "Id владельца комнаты");

    /**
     * The column <code>rules.rooms.rule_type</code>. Тип правил, например: 4e,
     * 5e, homebrew
     */
    public final TableField<RoomsRecord, String> RULE_TYPE = createField(DSL.name("rule_type"), SQLDataType.CLOB.nullable(false), this, "Тип правил, например: 4e, 5e, homebrew");

    private Rooms(Name alias, Table<RoomsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rooms(Name alias, Table<RoomsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Реплика информации о комнате из core микросервиса"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.rooms</code> table reference
     */
    public Rooms(String alias) {
        this(DSL.name(alias), ROOMS);
    }

    /**
     * Create an aliased <code>rules.rooms</code> table reference
     */
    public Rooms(Name alias) {
        this(alias, ROOMS);
    }

    /**
     * Create a <code>rules.rooms</code> table reference
     */
    public Rooms() {
        this(DSL.name("rooms"), null);
    }

    public <O extends Record> Rooms(Table<O> path, ForeignKey<O, RoomsRecord> childPath, InverseForeignKey<O, RoomsRecord> parentPath) {
        super(path, childPath, parentPath, ROOMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoomsPath extends Rooms implements Path<RoomsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoomsPath(Table<O> path, ForeignKey<O, RoomsRecord> childPath, InverseForeignKey<O, RoomsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoomsPath(Name alias, Table<RoomsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoomsPath as(String alias) {
            return new RoomsPath(DSL.name(alias), this);
        }

        @Override
        public RoomsPath as(Name alias) {
            return new RoomsPath(alias, this);
        }

        @Override
        public RoomsPath as(Table<?> alias) {
            return new RoomsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<RoomsRecord> getPrimaryKey() {
        return Keys.ROOMS_PKEY;
    }

    private transient AbilitiesPath _abilities;

    /**
     * Get the implicit to-many join path to the <code>rules.abilities</code>
     * table
     */
    public AbilitiesPath abilities() {
        if (_abilities == null)
            _abilities = new AbilitiesPath(this, null, Keys.ABILITIES__FKABILITIES898405.getInverseKey());

        return _abilities;
    }

    private transient ClassesPath _classes;

    /**
     * Get the implicit to-many join path to the <code>rules.classes</code>
     * table
     */
    public ClassesPath classes() {
        if (_classes == null)
            _classes = new ClassesPath(this, null, Keys.CLASSES__FKCLASSES862752.getInverseKey());

        return _classes;
    }

    private transient RacesPath _races;

    /**
     * Get the implicit to-many join path to the <code>rules.races</code> table
     */
    public RacesPath races() {
        if (_races == null)
            _races = new RacesPath(this, null, Keys.RACES__FKRACES214766.getInverseKey());

        return _races;
    }

    @Override
    public Rooms as(String alias) {
        return new Rooms(DSL.name(alias), this);
    }

    @Override
    public Rooms as(Name alias) {
        return new Rooms(alias, this);
    }

    @Override
    public Rooms as(Table<?> alias) {
        return new Rooms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(String name) {
        return new Rooms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(Name name) {
        return new Rooms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rooms rename(Table<?> name) {
        return new Rooms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Condition condition) {
        return new Rooms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Rooms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Rooms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
