/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RoomRulebookContentRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomRulebookContent extends TableImpl<RoomRulebookContentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.room_rulebook_content</code>
     */
    public static final RoomRulebookContent ROOM_RULEBOOK_CONTENT = new RoomRulebookContent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRulebookContentRecord> getRecordType() {
        return RoomRulebookContentRecord.class;
    }

    /**
     * The column <code>rules.room_rulebook_content.room_id</code>.
     */
    public final TableField<RoomRulebookContentRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.room_rulebook_content.content_id</code>.
     */
    public final TableField<RoomRulebookContentRecord, UUID> CONTENT_ID = createField(DSL.name("content_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.room_rulebook_content.created_at</code>.
     */
    public final TableField<RoomRulebookContentRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private RoomRulebookContent(Name alias, Table<RoomRulebookContentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoomRulebookContent(Name alias, Table<RoomRulebookContentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.room_rulebook_content</code> table
     * reference
     */
    public RoomRulebookContent(String alias) {
        this(DSL.name(alias), ROOM_RULEBOOK_CONTENT);
    }

    /**
     * Create an aliased <code>rules.room_rulebook_content</code> table
     * reference
     */
    public RoomRulebookContent(Name alias) {
        this(alias, ROOM_RULEBOOK_CONTENT);
    }

    /**
     * Create a <code>rules.room_rulebook_content</code> table reference
     */
    public RoomRulebookContent() {
        this(DSL.name("room_rulebook_content"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROOM_RULEBOOK_CONTENT_ROOM_IDX);
    }

    @Override
    public UniqueKey<RoomRulebookContentRecord> getPrimaryKey() {
        return Keys.ROOM_RULEBOOK_CONTENT_PKEY;
    }

    @Override
    public RoomRulebookContent as(String alias) {
        return new RoomRulebookContent(DSL.name(alias), this);
    }

    @Override
    public RoomRulebookContent as(Name alias) {
        return new RoomRulebookContent(alias, this);
    }

    @Override
    public RoomRulebookContent as(Table<?> alias) {
        return new RoomRulebookContent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookContent rename(String name) {
        return new RoomRulebookContent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookContent rename(Name name) {
        return new RoomRulebookContent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookContent rename(Table<?> name) {
        return new RoomRulebookContent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent where(Condition condition) {
        return new RoomRulebookContent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookContent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookContent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookContent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookContent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookContent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
