/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.RulebookBundle.RulebookBundlePath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RoomRulebookBundleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomRulebookBundle extends TableImpl<RoomRulebookBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.room_rulebook_bundle</code>
     */
    public static final RoomRulebookBundle ROOM_RULEBOOK_BUNDLE = new RoomRulebookBundle();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomRulebookBundleRecord> getRecordType() {
        return RoomRulebookBundleRecord.class;
    }

    /**
     * The column <code>rules.room_rulebook_bundle.room_id</code>.
     */
    public final TableField<RoomRulebookBundleRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.room_rulebook_bundle.rulebook_bundle_id</code>.
     */
    public final TableField<RoomRulebookBundleRecord, UUID> RULEBOOK_BUNDLE_ID = createField(DSL.name("rulebook_bundle_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.room_rulebook_bundle.created_at</code>.
     */
    public final TableField<RoomRulebookBundleRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private RoomRulebookBundle(Name alias, Table<RoomRulebookBundleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoomRulebookBundle(Name alias, Table<RoomRulebookBundleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.room_rulebook_bundle</code> table reference
     */
    public RoomRulebookBundle(String alias) {
        this(DSL.name(alias), ROOM_RULEBOOK_BUNDLE);
    }

    /**
     * Create an aliased <code>rules.room_rulebook_bundle</code> table reference
     */
    public RoomRulebookBundle(Name alias) {
        this(alias, ROOM_RULEBOOK_BUNDLE);
    }

    /**
     * Create a <code>rules.room_rulebook_bundle</code> table reference
     */
    public RoomRulebookBundle() {
        this(DSL.name("room_rulebook_bundle"), null);
    }

    public <O extends Record> RoomRulebookBundle(Table<O> path, ForeignKey<O, RoomRulebookBundleRecord> childPath, InverseForeignKey<O, RoomRulebookBundleRecord> parentPath) {
        super(path, childPath, parentPath, ROOM_RULEBOOK_BUNDLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoomRulebookBundlePath extends RoomRulebookBundle implements Path<RoomRulebookBundleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoomRulebookBundlePath(Table<O> path, ForeignKey<O, RoomRulebookBundleRecord> childPath, InverseForeignKey<O, RoomRulebookBundleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoomRulebookBundlePath(Name alias, Table<RoomRulebookBundleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoomRulebookBundlePath as(String alias) {
            return new RoomRulebookBundlePath(DSL.name(alias), this);
        }

        @Override
        public RoomRulebookBundlePath as(Name alias) {
            return new RoomRulebookBundlePath(alias, this);
        }

        @Override
        public RoomRulebookBundlePath as(Table<?> alias) {
            return new RoomRulebookBundlePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ROOM_RULEBOOK_BUNDLE_ROOM_IDX);
    }

    @Override
    public UniqueKey<RoomRulebookBundleRecord> getPrimaryKey() {
        return Keys.ROOM_RULEBOOK_BUNDLE_PKEY;
    }

    @Override
    public List<ForeignKey<RoomRulebookBundleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROOM_RULEBOOK_BUNDLE__FK_ROOM_RULEBOOK_BUNDLE);
    }

    private transient RulebookBundlePath _rulebookBundle;

    /**
     * Get the implicit join path to the <code>rules.rulebook_bundle</code>
     * table.
     */
    public RulebookBundlePath rulebookBundle() {
        if (_rulebookBundle == null)
            _rulebookBundle = new RulebookBundlePath(this, Keys.ROOM_RULEBOOK_BUNDLE__FK_ROOM_RULEBOOK_BUNDLE, null);

        return _rulebookBundle;
    }

    @Override
    public RoomRulebookBundle as(String alias) {
        return new RoomRulebookBundle(DSL.name(alias), this);
    }

    @Override
    public RoomRulebookBundle as(Name alias) {
        return new RoomRulebookBundle(alias, this);
    }

    @Override
    public RoomRulebookBundle as(Table<?> alias) {
        return new RoomRulebookBundle(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookBundle rename(String name) {
        return new RoomRulebookBundle(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookBundle rename(Name name) {
        return new RoomRulebookBundle(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoomRulebookBundle rename(Table<?> name) {
        return new RoomRulebookBundle(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle where(Condition condition) {
        return new RoomRulebookBundle(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookBundle where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookBundle where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookBundle where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoomRulebookBundle where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoomRulebookBundle whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
