/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.Abilities.AbilitiesPath;
import com.jiubredeemer.rulebook.dal.entity.tables.records.SkillsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Кастомные навыки существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Skills extends TableImpl<SkillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.skills</code>
     */
    public static final Skills SKILLS = new Skills();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SkillsRecord> getRecordType() {
        return SkillsRecord.class;
    }

    /**
     * The column <code>rules.skills.id</code>.
     */
    public final TableField<SkillsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.skills.name</code>. Название навыка
     */
    public final TableField<SkillsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Название навыка");

    /**
     * The column <code>rules.skills.code</code>. Краткий код навыка
     */
    public final TableField<SkillsRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "Краткий код навыка");

    /**
     * The column <code>rules.skills.depend_on_ability_id</code>. Зависимость
     * навыка от характеристики
     */
    public final TableField<SkillsRecord, UUID> DEPEND_ON_ABILITY_ID = createField(DSL.name("depend_on_ability_id"), SQLDataType.UUID.nullable(false), this, "Зависимость навыка от характеристики");

    private Skills(Name alias, Table<SkillsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Skills(Name alias, Table<SkillsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Кастомные навыки существ (для homebrew игр)"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.skills</code> table reference
     */
    public Skills(String alias) {
        this(DSL.name(alias), SKILLS);
    }

    /**
     * Create an aliased <code>rules.skills</code> table reference
     */
    public Skills(Name alias) {
        this(alias, SKILLS);
    }

    /**
     * Create a <code>rules.skills</code> table reference
     */
    public Skills() {
        this(DSL.name("skills"), null);
    }

    public <O extends Record> Skills(Table<O> path, ForeignKey<O, SkillsRecord> childPath, InverseForeignKey<O, SkillsRecord> parentPath) {
        super(path, childPath, parentPath, SKILLS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SkillsPath extends Skills implements Path<SkillsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SkillsPath(Table<O> path, ForeignKey<O, SkillsRecord> childPath, InverseForeignKey<O, SkillsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SkillsPath(Name alias, Table<SkillsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SkillsPath as(String alias) {
            return new SkillsPath(DSL.name(alias), this);
        }

        @Override
        public SkillsPath as(Name alias) {
            return new SkillsPath(alias, this);
        }

        @Override
        public SkillsPath as(Table<?> alias) {
            return new SkillsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<SkillsRecord> getPrimaryKey() {
        return Keys.SKILLS_PKEY;
    }

    @Override
    public List<ForeignKey<SkillsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SKILLS__FKSKILLS69995);
    }

    private transient AbilitiesPath _abilities;

    /**
     * Get the implicit join path to the <code>rules.abilities</code> table.
     */
    public AbilitiesPath abilities() {
        if (_abilities == null)
            _abilities = new AbilitiesPath(this, Keys.SKILLS__FKSKILLS69995, null);

        return _abilities;
    }

    @Override
    public Skills as(String alias) {
        return new Skills(DSL.name(alias), this);
    }

    @Override
    public Skills as(Name alias) {
        return new Skills(alias, this);
    }

    @Override
    public Skills as(Table<?> alias) {
        return new Skills(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Skills rename(String name) {
        return new Skills(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Skills rename(Name name) {
        return new Skills(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Skills rename(Table<?> name) {
        return new Skills(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills where(Condition condition) {
        return new Skills(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Skills where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Skills where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Skills where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Skills where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Skills whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
