/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Srd_2024BackgroundRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Srd_2024Background extends TableImpl<Srd_2024BackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.srd_2024_background</code>
     */
    public static final Srd_2024Background SRD_2024_BACKGROUND = new Srd_2024Background();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Srd_2024BackgroundRecord> getRecordType() {
        return Srd_2024BackgroundRecord.class;
    }

    /**
     * The column <code>rules.srd_2024_background.id</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.srd_2024_background.name</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.srd_2024_background.description</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.srd_2024_background.code</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.srd_2024_background.img_url</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>rules.srd_2024_background.background_stats_id</code>.
     */
    public final TableField<Srd_2024BackgroundRecord, UUID> BACKGROUND_STATS_ID = createField(DSL.name("background_stats_id"), SQLDataType.UUID.nullable(false), this, "");

    private Srd_2024Background(Name alias, Table<Srd_2024BackgroundRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Srd_2024Background(Name alias, Table<Srd_2024BackgroundRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.srd_2024_background</code> table reference
     */
    public Srd_2024Background(String alias) {
        this(DSL.name(alias), SRD_2024_BACKGROUND);
    }

    /**
     * Create an aliased <code>rules.srd_2024_background</code> table reference
     */
    public Srd_2024Background(Name alias) {
        this(alias, SRD_2024_BACKGROUND);
    }

    /**
     * Create a <code>rules.srd_2024_background</code> table reference
     */
    public Srd_2024Background() {
        this(DSL.name("srd_2024_background"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public UniqueKey<Srd_2024BackgroundRecord> getPrimaryKey() {
        return Keys.SRD_2024_BACKGROUND_PKEY;
    }

    @Override
    public Srd_2024Background as(String alias) {
        return new Srd_2024Background(DSL.name(alias), this);
    }

    @Override
    public Srd_2024Background as(Name alias) {
        return new Srd_2024Background(alias, this);
    }

    @Override
    public Srd_2024Background as(Table<?> alias) {
        return new Srd_2024Background(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Srd_2024Background rename(String name) {
        return new Srd_2024Background(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Srd_2024Background rename(Name name) {
        return new Srd_2024Background(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Srd_2024Background rename(Table<?> name) {
        return new Srd_2024Background(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background where(Condition condition) {
        return new Srd_2024Background(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Srd_2024Background where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Srd_2024Background where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Srd_2024Background where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Srd_2024Background where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Srd_2024Background whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
