/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables;


import com.jiubredeemer.rulebook.dal.entity.Indexes;
import com.jiubredeemer.rulebook.dal.entity.Keys;
import com.jiubredeemer.rulebook.dal.entity.Rules;
import com.jiubredeemer.rulebook.dal.entity.tables.records.UsersBlueprintRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersBlueprint extends TableImpl<UsersBlueprintRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules.users_blueprint</code>
     */
    public static final UsersBlueprint USERS_BLUEPRINT = new UsersBlueprint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersBlueprintRecord> getRecordType() {
        return UsersBlueprintRecord.class;
    }

    /**
     * The column <code>rules.users_blueprint.id</code>.
     */
    public final TableField<UsersBlueprintRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.room_id</code>.
     */
    public final TableField<UsersBlueprintRecord, UUID> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.creator_id</code>.
     */
    public final TableField<UsersBlueprintRecord, UUID> CREATOR_ID = createField(DSL.name("creator_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>rules.users_blueprint.code</code>.
     */
    public final TableField<UsersBlueprintRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.name</code>.
     */
    public final TableField<UsersBlueprintRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.description</code>.
     */
    public final TableField<UsersBlueprintRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.users_blueprint.group_code</code>.
     */
    public final TableField<UsersBlueprintRecord, String> GROUP_CODE = createField(DSL.name("group_code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.required_level</code>.
     */
    public final TableField<UsersBlueprintRecord, Integer> REQUIRED_LEVEL = createField(DSL.name("required_level"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rules.users_blueprint.customization</code>.
     */
    public final TableField<UsersBlueprintRecord, String> CUSTOMIZATION = createField(DSL.name("customization"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'NO'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rules.users_blueprint.item_id</code>.
     */
    public final TableField<UsersBlueprintRecord, UUID> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>rules.users_blueprint.img_url</code>.
     */
    public final TableField<UsersBlueprintRecord, String> IMG_URL = createField(DSL.name("img_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>rules.users_blueprint.hidden</code>.
     */
    public final TableField<UsersBlueprintRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>rules.users_blueprint.created_at</code>.
     */
    public final TableField<UsersBlueprintRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private UsersBlueprint(Name alias, Table<UsersBlueprintRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UsersBlueprint(Name alias, Table<UsersBlueprintRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>rules.users_blueprint</code> table reference
     */
    public UsersBlueprint(String alias) {
        this(DSL.name(alias), USERS_BLUEPRINT);
    }

    /**
     * Create an aliased <code>rules.users_blueprint</code> table reference
     */
    public UsersBlueprint(Name alias) {
        this(alias, USERS_BLUEPRINT);
    }

    /**
     * Create a <code>rules.users_blueprint</code> table reference
     */
    public UsersBlueprint() {
        this(DSL.name("users_blueprint"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Rules.RULES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USERS_BLUEPRINT_GROUP_CODE_IDX, Indexes.USERS_BLUEPRINT_ROOM_IDX);
    }

    @Override
    public UniqueKey<UsersBlueprintRecord> getPrimaryKey() {
        return Keys.USERS_BLUEPRINT_PKEY;
    }

    @Override
    public UsersBlueprint as(String alias) {
        return new UsersBlueprint(DSL.name(alias), this);
    }

    @Override
    public UsersBlueprint as(Name alias) {
        return new UsersBlueprint(alias, this);
    }

    @Override
    public UsersBlueprint as(Table<?> alias) {
        return new UsersBlueprint(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersBlueprint rename(String name) {
        return new UsersBlueprint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersBlueprint rename(Name name) {
        return new UsersBlueprint(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersBlueprint rename(Table<?> name) {
        return new UsersBlueprint(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint where(Condition condition) {
        return new UsersBlueprint(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersBlueprint where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersBlueprint where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersBlueprint where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsersBlueprint where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsersBlueprint whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
