server:
  port: 8081

spring:
  application:
    name: rulebook
  datasource:
    password: pd
    url: jdbc:postgresql://80.93.62.19:5432/rule_book
    username: pd
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

jooq:
  generator:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      with-input-schema: rules
      with-includes: .*
    target:
      package-name: com.jiubredeemer.rulebook.dal.entity
      directory: D:/Work/Pets/ProjectD/rulebook/src/main/kotlin
