/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Abilities;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkills;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits;
import com.jiubredeemer.rulebook.dal.entity.tables.Races;
import com.jiubredeemer.rulebook.dal.entity.tables.Skills;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in rules.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ABILITIES_ROOM_ID = Internal.createIndex(DSL.name("abilities_room_id"), Abilities.ABILITIES, new OrderField[] { Abilities.ABILITIES.ROOM_ID }, false);
    public static final Index CLASSES_ROOM_ID = Internal.createIndex(DSL.name("classes_room_id"), Classes.CLASSES, new OrderField[] { Classes.CLASSES.ROOM_ID }, false);
    public static final Index DEFAULT_5E_SKILLS_DEPEND_ON_ABILITY = Internal.createIndex(DSL.name("default_5e_skills_depend_on_ability"), Default_5eSkills.DEFAULT_5E_SKILLS, new OrderField[] { Default_5eSkills.DEFAULT_5E_SKILLS.DEPEND_ON_ABILITY }, false);
    public static final Index RACE_PROFICIENCIES_RACE_STATS_ID = Internal.createIndex(DSL.name("race_proficiencies_race_stats_id"), RaceProficiencies.RACE_PROFICIENCIES, new OrderField[] { RaceProficiencies.RACE_PROFICIENCIES.RACE_STATS_ID }, false);
    public static final Index RACE_TRAITS_RACE_STATS_ID = Internal.createIndex(DSL.name("race_traits_race_stats_id"), RaceTraits.RACE_TRAITS, new OrderField[] { RaceTraits.RACE_TRAITS.RACE_STATS_ID }, false);
    public static final Index RACES_ROOM_ID = Internal.createIndex(DSL.name("races_room_id"), Races.RACES, new OrderField[] { Races.RACES.ROOM_ID }, false);
    public static final Index SKILLS_DEPEND_ON_ABILITY_ID = Internal.createIndex(DSL.name("skills_depend_on_ability_id"), Skills.SKILLS, new OrderField[] { Skills.SKILLS.DEPEND_ON_ABILITY_ID }, false);
}
