/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Abilities;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbilities;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClasses;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRaces;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkills;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits;
import com.jiubredeemer.rulebook.dal.entity.tables.Races;
import com.jiubredeemer.rulebook.dal.entity.tables.Rooms;
import com.jiubredeemer.rulebook.dal.entity.tables.Skills;
import com.jiubredeemer.rulebook.dal.entity.tables.records.AbilitiesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.ClassProficienciesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.ClassStatsRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.ClassesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eAbilitiesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eClassesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eRacesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.Default_5eSkillsRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceProficienciesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceStatsRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RaceTraitsRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RacesRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.RoomsRecord;
import com.jiubredeemer.rulebook.dal.entity.tables.records.SkillsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * rules.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AbilitiesRecord> ABILITIES_PKEY = Internal.createUniqueKey(Abilities.ABILITIES, DSL.name("abilities_pkey"), new TableField[] { Abilities.ABILITIES.ID }, true);
    public static final UniqueKey<ClassProficienciesRecord> CLASS_PROFICIENCIES_PKEY = Internal.createUniqueKey(ClassProficiencies.CLASS_PROFICIENCIES, DSL.name("class_proficiencies_pkey"), new TableField[] { ClassProficiencies.CLASS_PROFICIENCIES.ID }, true);
    public static final UniqueKey<ClassStatsRecord> CLASS_STATS_PKEY = Internal.createUniqueKey(ClassStats.CLASS_STATS, DSL.name("class_stats_pkey"), new TableField[] { ClassStats.CLASS_STATS.ID }, true);
    public static final UniqueKey<ClassesRecord> CLASSES_PKEY = Internal.createUniqueKey(Classes.CLASSES, DSL.name("classes_pkey"), new TableField[] { Classes.CLASSES.ID }, true);
    public static final UniqueKey<Default_5eAbilitiesRecord> DEFAULT_5E_ABILITIES_PKEY = Internal.createUniqueKey(Default_5eAbilities.DEFAULT_5E_ABILITIES, DSL.name("default_5e_abilities_pkey"), new TableField[] { Default_5eAbilities.DEFAULT_5E_ABILITIES.ID }, true);
    public static final UniqueKey<Default_5eClassesRecord> DEFAULT_5E_CLASSES_PKEY = Internal.createUniqueKey(Default_5eClasses.DEFAULT_5E_CLASSES, DSL.name("default_5e_classes_pkey"), new TableField[] { Default_5eClasses.DEFAULT_5E_CLASSES.ID }, true);
    public static final UniqueKey<Default_5eRacesRecord> DEFAULT_5E_RACES_PKEY = Internal.createUniqueKey(Default_5eRaces.DEFAULT_5E_RACES, DSL.name("default_5e_races_pkey"), new TableField[] { Default_5eRaces.DEFAULT_5E_RACES.ID }, true);
    public static final UniqueKey<Default_5eSkillsRecord> DEFAULT_5E_SKILLS_PKEY = Internal.createUniqueKey(Default_5eSkills.DEFAULT_5E_SKILLS, DSL.name("default_5e_skills_pkey"), new TableField[] { Default_5eSkills.DEFAULT_5E_SKILLS.ID }, true);
    public static final UniqueKey<RaceProficienciesRecord> RACE_PROFICIENCIES_PKEY = Internal.createUniqueKey(RaceProficiencies.RACE_PROFICIENCIES, DSL.name("race_proficiencies_pkey"), new TableField[] { RaceProficiencies.RACE_PROFICIENCIES.ID }, true);
    public static final UniqueKey<RaceStatsRecord> RACE_STATS_PKEY = Internal.createUniqueKey(RaceStats.RACE_STATS, DSL.name("race_stats_pkey"), new TableField[] { RaceStats.RACE_STATS.ID }, true);
    public static final UniqueKey<RaceTraitsRecord> RACE_TRAITS_PKEY = Internal.createUniqueKey(RaceTraits.RACE_TRAITS, DSL.name("race_traits_pkey"), new TableField[] { RaceTraits.RACE_TRAITS.ID }, true);
    public static final UniqueKey<RacesRecord> RACES_PKEY = Internal.createUniqueKey(Races.RACES, DSL.name("races_pkey"), new TableField[] { Races.RACES.ID }, true);
    public static final UniqueKey<RoomsRecord> ROOMS_PKEY = Internal.createUniqueKey(Rooms.ROOMS, DSL.name("rooms_pkey"), new TableField[] { Rooms.ROOMS.ROOM_ID }, true);
    public static final UniqueKey<SkillsRecord> SKILLS_PKEY = Internal.createUniqueKey(Skills.SKILLS, DSL.name("skills_pkey"), new TableField[] { Skills.SKILLS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AbilitiesRecord, RoomsRecord> ABILITIES__FKABILITIES898405 = Internal.createForeignKey(Abilities.ABILITIES, DSL.name("fkabilities898405"), new TableField[] { Abilities.ABILITIES.ROOM_ID }, Keys.ROOMS_PKEY, new TableField[] { Rooms.ROOMS.ROOM_ID }, true);
    public static final ForeignKey<ClassProficienciesRecord, ClassStatsRecord> CLASS_PROFICIENCIES__FKCLASS_PROF188640 = Internal.createForeignKey(ClassProficiencies.CLASS_PROFICIENCIES, DSL.name("fkclass_prof188640"), new TableField[] { ClassProficiencies.CLASS_PROFICIENCIES.CLASS_STATS_ID }, Keys.CLASS_STATS_PKEY, new TableField[] { ClassStats.CLASS_STATS.ID }, true);
    public static final ForeignKey<ClassesRecord, ClassStatsRecord> CLASSES__FKCLASSES375368 = Internal.createForeignKey(Classes.CLASSES, DSL.name("fkclasses375368"), new TableField[] { Classes.CLASSES.CLASS_STATS_ID }, Keys.CLASS_STATS_PKEY, new TableField[] { ClassStats.CLASS_STATS.ID }, true);
    public static final ForeignKey<ClassesRecord, RoomsRecord> CLASSES__FKCLASSES862752 = Internal.createForeignKey(Classes.CLASSES, DSL.name("fkclasses862752"), new TableField[] { Classes.CLASSES.ROOM_ID }, Keys.ROOMS_PKEY, new TableField[] { Rooms.ROOMS.ROOM_ID }, true);
    public static final ForeignKey<Default_5eClassesRecord, ClassStatsRecord> DEFAULT_5E_CLASSES__FKDEFAULT_5E174476 = Internal.createForeignKey(Default_5eClasses.DEFAULT_5E_CLASSES, DSL.name("fkdefault_5e174476"), new TableField[] { Default_5eClasses.DEFAULT_5E_CLASSES.CLASS_STATS_ID }, Keys.CLASS_STATS_PKEY, new TableField[] { ClassStats.CLASS_STATS.ID }, true);
    public static final ForeignKey<Default_5eRacesRecord, RaceStatsRecord> DEFAULT_5E_RACES__FKDEFAULT_5E40267 = Internal.createForeignKey(Default_5eRaces.DEFAULT_5E_RACES, DSL.name("fkdefault_5e40267"), new TableField[] { Default_5eRaces.DEFAULT_5E_RACES.RACE_STATS_ID }, Keys.RACE_STATS_PKEY, new TableField[] { RaceStats.RACE_STATS.ID }, true);
    public static final ForeignKey<Default_5eSkillsRecord, Default_5eAbilitiesRecord> DEFAULT_5E_SKILLS__FKDEFAULT_5E869303 = Internal.createForeignKey(Default_5eSkills.DEFAULT_5E_SKILLS, DSL.name("fkdefault_5e869303"), new TableField[] { Default_5eSkills.DEFAULT_5E_SKILLS.DEPEND_ON_ABILITY }, Keys.DEFAULT_5E_ABILITIES_PKEY, new TableField[] { Default_5eAbilities.DEFAULT_5E_ABILITIES.ID }, true);
    public static final ForeignKey<RaceProficienciesRecord, RaceStatsRecord> RACE_PROFICIENCIES__FKRACE_PROFI169598 = Internal.createForeignKey(RaceProficiencies.RACE_PROFICIENCIES, DSL.name("fkrace_profi169598"), new TableField[] { RaceProficiencies.RACE_PROFICIENCIES.RACE_STATS_ID }, Keys.RACE_STATS_PKEY, new TableField[] { RaceStats.RACE_STATS.ID }, true);
    public static final ForeignKey<RaceTraitsRecord, RaceStatsRecord> RACE_TRAITS__FKRACE_TRAIT331219 = Internal.createForeignKey(RaceTraits.RACE_TRAITS, DSL.name("fkrace_trait331219"), new TableField[] { RaceTraits.RACE_TRAITS.RACE_STATS_ID }, Keys.RACE_STATS_PKEY, new TableField[] { RaceStats.RACE_STATS.ID }, true);
    public static final ForeignKey<RacesRecord, RoomsRecord> RACES__FKRACES214766 = Internal.createForeignKey(Races.RACES, DSL.name("fkraces214766"), new TableField[] { Races.RACES.ROOM_ID }, Keys.ROOMS_PKEY, new TableField[] { Rooms.ROOMS.ROOM_ID }, true);
    public static final ForeignKey<RacesRecord, RaceStatsRecord> RACES__FKRACES292535 = Internal.createForeignKey(Races.RACES, DSL.name("fkraces292535"), new TableField[] { Races.RACES.RACE_STATS_ID }, Keys.RACE_STATS_PKEY, new TableField[] { RaceStats.RACE_STATS.ID }, true);
    public static final ForeignKey<SkillsRecord, AbilitiesRecord> SKILLS__FKSKILLS69995 = Internal.createForeignKey(Skills.SKILLS, DSL.name("fkskills69995"), new TableField[] { Skills.SKILLS.DEPEND_ON_ABILITY_ID }, Keys.ABILITIES_PKEY, new TableField[] { Abilities.ABILITIES.ID }, true);
}
