/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Ability;
import com.jiubredeemer.rulebook.dal.entity.tables.Background;
import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundProficiency;
import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundStats;
import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundTrait;
import com.jiubredeemer.rulebook.dal.entity.tables.Clazz;
import com.jiubredeemer.rulebook.dal.entity.tables.ClazzStats;
import com.jiubredeemer.rulebook.dal.entity.tables.DefaultEberronBackground;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Background;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Clazz;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Race;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbility;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClazz;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRace;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkill;
import com.jiubredeemer.rulebook.dal.entity.tables.Race;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiency;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTrait;
import com.jiubredeemer.rulebook.dal.entity.tables.Room;
import com.jiubredeemer.rulebook.dal.entity.tables.Skill;
import com.jiubredeemer.rulebook.dal.entity.tables.Srd_2024Background;
import com.jiubredeemer.rulebook.dal.entity.tables.Srd_2024Clazz;
import com.jiubredeemer.rulebook.dal.entity.tables.Srd_2024Race;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rules extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules</code>
     */
    public static final Rules RULES = new Rules();

    /**
     * Кастомные характеристики существ (для homebrew игр)
     */
    public final Ability ABILITY = Ability.ABILITY;

    /**
     * Предыстории
     */
    public final Background BACKGROUND = Background.BACKGROUND;

    /**
     * Владение навыком или инструментом от предыстории
     */
    public final BackgroundProficiency BACKGROUND_PROFICIENCY = BackgroundProficiency.BACKGROUND_PROFICIENCY;

    /**
     * Характеристики предыстории: три характеристики на выбор (+2/+1 или
     * +1/+1/+1)
     */
    public final BackgroundStats BACKGROUND_STATS = BackgroundStats.BACKGROUND_STATS;

    /**
     * Черта происхождения (Origin Feat), даруемая предысторией
     */
    public final BackgroundTrait BACKGROUND_TRAIT = BackgroundTrait.BACKGROUND_TRAIT;

    /**
     * The table <code>rules.clazz</code>.
     */
    public final Clazz CLAZZ = Clazz.CLAZZ;

    /**
     * The table <code>rules.clazz_stats</code>.
     */
    public final ClazzStats CLAZZ_STATS = ClazzStats.CLAZZ_STATS;

    /**
     * Предыстории по умолчанию для D&amp;D 2024 (PHB)
     */
    public final Default_2024Background DEFAULT_2024_BACKGROUND = Default_2024Background.DEFAULT_2024_BACKGROUND;

    /**
     * The table <code>rules.default_2024_clazz</code>.
     */
    public final Default_2024Clazz DEFAULT_2024_CLAZZ = Default_2024Clazz.DEFAULT_2024_CLAZZ;

    /**
     * The table <code>rules.default_2024_race</code>.
     */
    public final Default_2024Race DEFAULT_2024_RACE = Default_2024Race.DEFAULT_2024_RACE;

    /**
     * Характеристики существ по дефолтным правилам ДнД 5е
     */
    public final Default_5eAbility DEFAULT_5E_ABILITY = Default_5eAbility.DEFAULT_5E_ABILITY;

    /**
     * The table <code>rules.default_5e_clazz</code>.
     */
    public final Default_5eClazz DEFAULT_5E_CLAZZ = Default_5eClazz.DEFAULT_5E_CLAZZ;

    /**
     * The table <code>rules.default_5e_race</code>.
     */
    public final Default_5eRace DEFAULT_5E_RACE = Default_5eRace.DEFAULT_5E_RACE;

    /**
     * Навыки по дефолтным правилам DnD 5e
     */
    public final Default_5eSkill DEFAULT_5E_SKILL = Default_5eSkill.DEFAULT_5E_SKILL;

    /**
     * Предыстории по умолчанию для сеттинга Eberron (Eberron: Rising from the
     * Last War)
     */
    public final DefaultEberronBackground DEFAULT_EBERRON_BACKGROUND = DefaultEberronBackground.DEFAULT_EBERRON_BACKGROUND;

    /**
     * The table <code>rules.race</code>.
     */
    public final Race RACE = Race.RACE;

    /**
     * The table <code>rules.race_proficiency</code>.
     */
    public final RaceProficiency RACE_PROFICIENCY = RaceProficiency.RACE_PROFICIENCY;

    /**
     * The table <code>rules.race_stats</code>.
     */
    public final RaceStats RACE_STATS = RaceStats.RACE_STATS;

    /**
     * The table <code>rules.race_trait</code>.
     */
    public final RaceTrait RACE_TRAIT = RaceTrait.RACE_TRAIT;

    /**
     * Реплика информации о комнате из core микросервиса
     */
    public final Room ROOM = Room.ROOM;

    /**
     * Кастомные навыки существ (для homebrew игр)
     */
    public final Skill SKILL = Skill.SKILL;

    /**
     * The table <code>rules.srd_2024_background</code>.
     */
    public final Srd_2024Background SRD_2024_BACKGROUND = Srd_2024Background.SRD_2024_BACKGROUND;

    /**
     * The table <code>rules.srd_2024_clazz</code>.
     */
    public final Srd_2024Clazz SRD_2024_CLAZZ = Srd_2024Clazz.SRD_2024_CLAZZ;

    /**
     * The table <code>rules.srd_2024_race</code>.
     */
    public final Srd_2024Race SRD_2024_RACE = Srd_2024Race.SRD_2024_RACE;

    /**
     * No further instances allowed
     */
    private Rules() {
        super("rules", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Ability.ABILITY,
            Background.BACKGROUND,
            BackgroundProficiency.BACKGROUND_PROFICIENCY,
            BackgroundStats.BACKGROUND_STATS,
            BackgroundTrait.BACKGROUND_TRAIT,
            Clazz.CLAZZ,
            ClazzStats.CLAZZ_STATS,
            Default_2024Background.DEFAULT_2024_BACKGROUND,
            Default_2024Clazz.DEFAULT_2024_CLAZZ,
            Default_2024Race.DEFAULT_2024_RACE,
            Default_5eAbility.DEFAULT_5E_ABILITY,
            Default_5eClazz.DEFAULT_5E_CLAZZ,
            Default_5eRace.DEFAULT_5E_RACE,
            Default_5eSkill.DEFAULT_5E_SKILL,
            DefaultEberronBackground.DEFAULT_EBERRON_BACKGROUND,
            Race.RACE,
            RaceProficiency.RACE_PROFICIENCY,
            RaceStats.RACE_STATS,
            RaceTrait.RACE_TRAIT,
            Room.ROOM,
            Skill.SKILL,
            Srd_2024Background.SRD_2024_BACKGROUND,
            Srd_2024Clazz.SRD_2024_CLAZZ,
            Srd_2024Race.SRD_2024_RACE
        );
    }
}
