/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Abilities;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbilities;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClasses;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRaces;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkills;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits;
import com.jiubredeemer.rulebook.dal.entity.tables.Races;
import com.jiubredeemer.rulebook.dal.entity.tables.Rooms;
import com.jiubredeemer.rulebook.dal.entity.tables.Skills;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rules extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rules</code>
     */
    public static final Rules RULES = new Rules();

    /**
     * Кастомные характеристики существ (для homebrew игр)
     */
    public final Abilities ABILITIES = Abilities.ABILITIES;

    /**
     * The table <code>rules.class_stats</code>.
     */
    public final ClassStats CLASS_STATS = ClassStats.CLASS_STATS;

    /**
     * The table <code>rules.classes</code>.
     */
    public final Classes CLASSES = Classes.CLASSES;

    /**
     * Характеристики существ по дефолтным правилам ДнД 5е
     */
    public final Default_5eAbilities DEFAULT_5E_ABILITIES = Default_5eAbilities.DEFAULT_5E_ABILITIES;

    /**
     * The table <code>rules.default_5e_classes</code>.
     */
    public final Default_5eClasses DEFAULT_5E_CLASSES = Default_5eClasses.DEFAULT_5E_CLASSES;

    /**
     * The table <code>rules.default_5e_races</code>.
     */
    public final Default_5eRaces DEFAULT_5E_RACES = Default_5eRaces.DEFAULT_5E_RACES;

    /**
     * Навыки по дефолтным правилам DnD 5e
     */
    public final Default_5eSkills DEFAULT_5E_SKILLS = Default_5eSkills.DEFAULT_5E_SKILLS;

    /**
     * The table <code>rules.race_proficiencies</code>.
     */
    public final RaceProficiencies RACE_PROFICIENCIES = RaceProficiencies.RACE_PROFICIENCIES;

    /**
     * The table <code>rules.race_stats</code>.
     */
    public final RaceStats RACE_STATS = RaceStats.RACE_STATS;

    /**
     * The table <code>rules.race_traits</code>.
     */
    public final RaceTraits RACE_TRAITS = RaceTraits.RACE_TRAITS;

    /**
     * The table <code>rules.races</code>.
     */
    public final Races RACES = Races.RACES;

    /**
     * Реплика информации о комнате из core микросервиса
     */
    public final Rooms ROOMS = Rooms.ROOMS;

    /**
     * Кастомные навыки существ (для homebrew игр)
     */
    public final Skills SKILLS = Skills.SKILLS;

    /**
     * No further instances allowed
     */
    private Rules() {
        super("rules", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Abilities.ABILITIES,
            ClassStats.CLASS_STATS,
            Classes.CLASSES,
            Default_5eAbilities.DEFAULT_5E_ABILITIES,
            Default_5eClasses.DEFAULT_5E_CLASSES,
            Default_5eRaces.DEFAULT_5E_RACES,
            Default_5eSkills.DEFAULT_5E_SKILLS,
            RaceProficiencies.RACE_PROFICIENCIES,
            RaceStats.RACE_STATS,
            RaceTraits.RACE_TRAITS,
            Races.RACES,
            Rooms.ROOMS,
            Skills.SKILLS
        );
    }
}
