/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Ability;
import com.jiubredeemer.rulebook.dal.entity.tables.Clazz;
import com.jiubredeemer.rulebook.dal.entity.tables.ClazzStats;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Clazz;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Race;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbility;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClazz;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRace;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkill;
import com.jiubredeemer.rulebook.dal.entity.tables.Race;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiency;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTrait;
import com.jiubredeemer.rulebook.dal.entity.tables.Room;
import com.jiubredeemer.rulebook.dal.entity.tables.Skill;


/**
 * Convenience access to all tables in rules.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Кастомные характеристики существ (для homebrew игр)
     */
    public static final Ability ABILITY = Ability.ABILITY;

    /**
     * The table <code>rules.clazz</code>.
     */
    public static final Clazz CLAZZ = Clazz.CLAZZ;

    /**
     * The table <code>rules.clazz_stats</code>.
     */
    public static final ClazzStats CLAZZ_STATS = ClazzStats.CLAZZ_STATS;

    /**
     * The table <code>rules.default_2024_clazz</code>.
     */
    public static final Default_2024Clazz DEFAULT_2024_CLAZZ = Default_2024Clazz.DEFAULT_2024_CLAZZ;

    /**
     * The table <code>rules.default_2024_race</code>.
     */
    public static final Default_2024Race DEFAULT_2024_RACE = Default_2024Race.DEFAULT_2024_RACE;

    /**
     * Характеристики существ по дефолтным правилам ДнД 5е
     */
    public static final Default_5eAbility DEFAULT_5E_ABILITY = Default_5eAbility.DEFAULT_5E_ABILITY;

    /**
     * The table <code>rules.default_5e_clazz</code>.
     */
    public static final Default_5eClazz DEFAULT_5E_CLAZZ = Default_5eClazz.DEFAULT_5E_CLAZZ;

    /**
     * The table <code>rules.default_5e_race</code>.
     */
    public static final Default_5eRace DEFAULT_5E_RACE = Default_5eRace.DEFAULT_5E_RACE;

    /**
     * Навыки по дефолтным правилам DnD 5e
     */
    public static final Default_5eSkill DEFAULT_5E_SKILL = Default_5eSkill.DEFAULT_5E_SKILL;

    /**
     * The table <code>rules.race</code>.
     */
    public static final Race RACE = Race.RACE;

    /**
     * The table <code>rules.race_proficiency</code>.
     */
    public static final RaceProficiency RACE_PROFICIENCY = RaceProficiency.RACE_PROFICIENCY;

    /**
     * The table <code>rules.race_stats</code>.
     */
    public static final RaceStats RACE_STATS = RaceStats.RACE_STATS;

    /**
     * The table <code>rules.race_trait</code>.
     */
    public static final RaceTrait RACE_TRAIT = RaceTrait.RACE_TRAIT;

    /**
     * Реплика информации о комнате из core микросервиса
     */
    public static final Room ROOM = Room.ROOM;

    /**
     * Кастомные навыки существ (для homebrew игр)
     */
    public static final Skill SKILL = Skill.SKILL;
}
