/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity;


import com.jiubredeemer.rulebook.dal.entity.tables.Abilities;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats;
import com.jiubredeemer.rulebook.dal.entity.tables.Classes;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbilities;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClasses;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRaces;
import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkills;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;
import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits;
import com.jiubredeemer.rulebook.dal.entity.tables.Races;
import com.jiubredeemer.rulebook.dal.entity.tables.Rooms;
import com.jiubredeemer.rulebook.dal.entity.tables.Skills;


/**
 * Convenience access to all tables in rules.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Кастомные характеристики существ (для homebrew игр)
     */
    public static final Abilities ABILITIES = Abilities.ABILITIES;

    /**
     * The table <code>rules.class_proficiencies</code>.
     */
    public static final ClassProficiencies CLASS_PROFICIENCIES = ClassProficiencies.CLASS_PROFICIENCIES;

    /**
     * The table <code>rules.class_stats</code>.
     */
    public static final ClassStats CLASS_STATS = ClassStats.CLASS_STATS;

    /**
     * The table <code>rules.classes</code>.
     */
    public static final Classes CLASSES = Classes.CLASSES;

    /**
     * Характеристики существ по дефолтным правилам ДнД 5е
     */
    public static final Default_5eAbilities DEFAULT_5E_ABILITIES = Default_5eAbilities.DEFAULT_5E_ABILITIES;

    /**
     * The table <code>rules.default_5e_classes</code>.
     */
    public static final Default_5eClasses DEFAULT_5E_CLASSES = Default_5eClasses.DEFAULT_5E_CLASSES;

    /**
     * The table <code>rules.default_5e_races</code>.
     */
    public static final Default_5eRaces DEFAULT_5E_RACES = Default_5eRaces.DEFAULT_5E_RACES;

    /**
     * Навыки по дефолтным правилам DnD 5e
     */
    public static final Default_5eSkills DEFAULT_5E_SKILLS = Default_5eSkills.DEFAULT_5E_SKILLS;

    /**
     * The table <code>rules.race_proficiencies</code>.
     */
    public static final RaceProficiencies RACE_PROFICIENCIES = RaceProficiencies.RACE_PROFICIENCIES;

    /**
     * The table <code>rules.race_stats</code>.
     */
    public static final RaceStats RACE_STATS = RaceStats.RACE_STATS;

    /**
     * The table <code>rules.race_traits</code>.
     */
    public static final RaceTraits RACE_TRAITS = RaceTraits.RACE_TRAITS;

    /**
     * The table <code>rules.races</code>.
     */
    public static final Races RACES = Races.RACES;

    /**
     * Реплика информации о комнате из core микросервиса
     */
    public static final Rooms ROOMS = Rooms.ROOMS;

    /**
     * Кастомные навыки существ (для homebrew игр)
     */
    public static final Skills SKILLS = Skills.SKILLS;
}
