/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Ability;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Кастомные характеристики существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AbilityRecord extends UpdatableRecordImpl<AbilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.ability.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.ability.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.ability.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.ability.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.ability.name</code>. Название характеристики
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.ability.name</code>. Название характеристики
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.ability.code</code>. Краткий код характеристики
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.ability.code</code>. Краткий код характеристики
     */
    public String getCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbilityRecord
     */
    public AbilityRecord() {
        super(Ability.ABILITY);
    }

    /**
     * Create a detached, initialised AbilityRecord
     */
    public AbilityRecord(UUID id, UUID roomId, String name, String code) {
        super(Ability.ABILITY);

        setId(id);
        setRoomId(roomId);
        setName(name);
        setCode(code);
        resetChangedOnNotNull();
    }
}
