/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundStats;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Характеристики предыстории: три характеристики на выбор (+2/+1 или +1/+1/+1)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundStatsRecord extends UpdatableRecordImpl<BackgroundStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.background_stats.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.background_stats.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.background_stats.ability_modifiers</code>. Массив
     * из трёх кодов характеристик из rules.default_5e_ability (002): STR, DEX,
     * CON, INT, WIS, CHA. Источник: next.dnd.su, XPath
     * /html/body/main/div/div/div/section[2]/div/div/div[2]/ul/li[1]/text()
     * (строка «Характеристики: …»).
     */
    public void setAbilityModifiers(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.background_stats.ability_modifiers</code>. Массив
     * из трёх кодов характеристик из rules.default_5e_ability (002): STR, DEX,
     * CON, INT, WIS, CHA. Источник: next.dnd.su, XPath
     * /html/body/main/div/div/div/section[2]/div/div/div[2]/ul/li[1]/text()
     * (строка «Характеристики: …»).
     */
    public JSONB getAbilityModifiers() {
        return (JSONB) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackgroundStatsRecord
     */
    public BackgroundStatsRecord() {
        super(BackgroundStats.BACKGROUND_STATS);
    }

    /**
     * Create a detached, initialised BackgroundStatsRecord
     */
    public BackgroundStatsRecord(UUID id, JSONB abilityModifiers) {
        super(BackgroundStats.BACKGROUND_STATS);

        setId(id);
        setAbilityModifiers(abilityModifiers);
        resetChangedOnNotNull();
    }
}
