/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundProficiency;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Владение навыком или инструментом от предыстории
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundProficiencyRecord extends UpdatableRecordImpl<BackgroundProficiencyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.background_proficiency.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.background_proficiency.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.background_proficiency.background_stats_id</code>.
     */
    public void setBackgroundStatsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.background_proficiency.background_stats_id</code>.
     */
    public UUID getBackgroundStatsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.background_proficiency.type</code>. SKILL или TOOL
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.background_proficiency.type</code>. SKILL или TOOL
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.background_proficiency.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.background_proficiency.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackgroundProficiencyRecord
     */
    public BackgroundProficiencyRecord() {
        super(BackgroundProficiency.BACKGROUND_PROFICIENCY);
    }

    /**
     * Create a detached, initialised BackgroundProficiencyRecord
     */
    public BackgroundProficiencyRecord(UUID id, UUID backgroundStatsId, String type, String code) {
        super(BackgroundProficiency.BACKGROUND_PROFICIENCY);

        setId(id);
        setBackgroundStatsId(backgroundStatsId);
        setType(type);
        setCode(code);
        resetChangedOnNotNull();
    }
}
