/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.BackgroundTrait;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Черта происхождения (Origin Feat), даруемая предысторией
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BackgroundTraitRecord extends UpdatableRecordImpl<BackgroundTraitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.background_trait.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.background_trait.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.background_trait.background_stats_id</code>.
     */
    public void setBackgroundStatsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.background_trait.background_stats_id</code>.
     */
    public UUID getBackgroundStatsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.background_trait.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.background_trait.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.background_trait.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.background_trait.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.background_trait.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.background_trait.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BackgroundTraitRecord
     */
    public BackgroundTraitRecord() {
        super(BackgroundTrait.BACKGROUND_TRAIT);
    }

    /**
     * Create a detached, initialised BackgroundTraitRecord
     */
    public BackgroundTraitRecord(UUID id, UUID backgroundStatsId, String name, String code, String description) {
        super(BackgroundTrait.BACKGROUND_TRAIT);

        setId(id);
        setBackgroundStatsId(backgroundStatsId);
        setName(name);
        setCode(code);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
