/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Blueprint;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BlueprintRecord extends UpdatableRecordImpl<BlueprintRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.blueprint.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.blueprint.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.blueprint.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.blueprint.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.blueprint.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.blueprint.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.blueprint.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.blueprint.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.blueprint.group_code</code>.
     */
    public void setGroupCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.blueprint.group_code</code>.
     */
    public String getGroupCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rules.blueprint.required_level</code>.
     */
    public void setRequiredLevel(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.blueprint.required_level</code>.
     */
    public Integer getRequiredLevel() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rules.blueprint.customization</code>.
     */
    public void setCustomization(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rules.blueprint.customization</code>.
     */
    public String getCustomization() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rules.blueprint.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>rules.blueprint.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>rules.blueprint.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>rules.blueprint.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>rules.blueprint.bundle_id</code>.
     */
    public void setBundleId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>rules.blueprint.bundle_id</code>.
     */
    public UUID getBundleId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>rules.blueprint.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>rules.blueprint.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlueprintRecord
     */
    public BlueprintRecord() {
        super(Blueprint.BLUEPRINT);
    }

    /**
     * Create a detached, initialised BlueprintRecord
     */
    public BlueprintRecord(UUID id, String code, String name, String description, String groupCode, Integer requiredLevel, String customization, UUID itemId, String imgUrl, UUID bundleId, Boolean hidden) {
        super(Blueprint.BLUEPRINT);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setGroupCode(groupCode);
        setRequiredLevel(requiredLevel);
        setCustomization(customization);
        setItemId(itemId);
        setImgUrl(imgUrl);
        setBundleId(bundleId);
        setHidden(hidden);
        resetChangedOnNotNull();
    }
}
