/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.ClassStats;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassStatsRecord extends UpdatableRecordImpl<ClassStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.class_stats.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.class_stats.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.class_stats.hp_dice</code>.
     */
    public void setHpDice(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.class_stats.hp_dice</code>.
     */
    public String getHpDice() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.class_stats.start_hp</code>.
     */
    public void setStartHp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.class_stats.start_hp</code>.
     */
    public String getStartHp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.class_stats.saving_throws_abilities</code>.
     * ["WIS", "INT"]
     */
    public void setSavingThrowsAbilities(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.class_stats.saving_throws_abilities</code>.
     * ["WIS", "INT"]
     */
    public JSONB getSavingThrowsAbilities() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>rules.class_stats.skills</code>. Навыки, которыми может
     * владеть класс: {"count" : 2, "list" : "WIS", "INT"}
     */
    public void setSkills(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.class_stats.skills</code>. Навыки, которыми может
     * владеть класс: {"count" : 2, "list" : "WIS", "INT"}
     */
    public JSONB getSkills() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassStatsRecord
     */
    public ClassStatsRecord() {
        super(ClassStats.CLASS_STATS);
    }

    /**
     * Create a detached, initialised ClassStatsRecord
     */
    public ClassStatsRecord(UUID id, String hpDice, String startHp, JSONB savingThrowsAbilities, JSONB skills) {
        super(ClassStats.CLASS_STATS);

        setId(id);
        setHpDice(hpDice);
        setStartHp(startHp);
        setSavingThrowsAbilities(savingThrowsAbilities);
        setSkills(skills);
        resetChangedOnNotNull();
    }
}
