/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Classes;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassesRecord extends UpdatableRecordImpl<ClassesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.classes.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.classes.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.classes.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.classes.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.classes.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.classes.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.classes.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.classes.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.classes.class_stats_id</code>.
     */
    public void setClassStatsId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.classes.class_stats_id</code>.
     */
    public UUID getClassStatsId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassesRecord
     */
    public ClassesRecord() {
        super(Classes.CLASSES);
    }

    /**
     * Create a detached, initialised ClassesRecord
     */
    public ClassesRecord(UUID id, UUID roomId, String name, String code, UUID classStatsId) {
        super(Classes.CLASSES);

        setId(id);
        setRoomId(roomId);
        setName(name);
        setCode(code);
        setClassStatsId(classStatsId);
        resetChangedOnNotNull();
    }
}
