/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.ClassProficiencies;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassProficienciesRecord extends UpdatableRecordImpl<ClassProficienciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.class_proficiencies.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.class_proficiencies.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.class_proficiencies.class_stats_id</code>.
     */
    public void setClassStatsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.class_proficiencies.class_stats_id</code>.
     */
    public UUID getClassStatsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.class_proficiencies.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.class_proficiencies.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.class_proficiencies.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.class_proficiencies.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassProficienciesRecord
     */
    public ClassProficienciesRecord() {
        super(ClassProficiencies.CLASS_PROFICIENCIES);
    }

    /**
     * Create a detached, initialised ClassProficienciesRecord
     */
    public ClassProficienciesRecord(UUID id, UUID classStatsId, String type, String code) {
        super(ClassProficiencies.CLASS_PROFICIENCIES);

        setId(id);
        setClassStatsId(classStatsId);
        setType(type);
        setCode(code);
        resetChangedOnNotNull();
    }
}
