/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.ClazzStats;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClazzStatsRecord extends UpdatableRecordImpl<ClazzStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.clazz_stats.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.clazz_stats.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.clazz_stats.hp_dice</code>.
     */
    public void setHpDice(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.clazz_stats.hp_dice</code>.
     */
    public String getHpDice() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.clazz_stats.start_hp</code>.
     */
    public void setStartHp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.clazz_stats.start_hp</code>.
     */
    public String getStartHp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.clazz_stats.saving_throws_ability</code>. ["WIS",
     * "INT"]
     */
    public void setSavingThrowsAbility(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.clazz_stats.saving_throws_ability</code>. ["WIS",
     * "INT"]
     */
    public JSONB getSavingThrowsAbility() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>rules.clazz_stats.available_skills</code>. Навыки,
     * которыми может владеть класс: {"count" : 2, "list" : "WIS", "INT"}
     */
    public void setAvailableSkills(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.clazz_stats.available_skills</code>. Навыки,
     * которыми может владеть класс: {"count" : 2, "list" : "WIS", "INT"}
     */
    public JSONB getAvailableSkills() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClazzStatsRecord
     */
    public ClazzStatsRecord() {
        super(ClazzStats.CLAZZ_STATS);
    }

    /**
     * Create a detached, initialised ClazzStatsRecord
     */
    public ClazzStatsRecord(UUID id, String hpDice, String startHp, JSONB savingThrowsAbility, JSONB availableSkills) {
        super(ClazzStats.CLAZZ_STATS);

        setId(id);
        setHpDice(hpDice);
        setStartHp(startHp);
        setSavingThrowsAbility(savingThrowsAbility);
        setAvailableSkills(availableSkills);
        resetChangedOnNotNull();
    }
}
