/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Clazz;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClazzRecord extends UpdatableRecordImpl<ClazzRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.clazz.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.clazz.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.clazz.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.clazz.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.clazz.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.clazz.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.clazz.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.clazz.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.clazz.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.clazz.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rules.clazz.clazz_stats_id</code>.
     */
    public void setClazzStatsId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.clazz.clazz_stats_id</code>.
     */
    public UUID getClazzStatsId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>rules.clazz.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rules.clazz.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rules.clazz.group_code</code>.
     */
    public void setGroupCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rules.clazz.group_code</code>.
     */
    public String getGroupCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rules.clazz.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>rules.clazz.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClazzRecord
     */
    public ClazzRecord() {
        super(Clazz.CLAZZ);
    }

    /**
     * Create a detached, initialised ClazzRecord
     */
    public ClazzRecord(UUID id, UUID roomId, String name, String description, String code, UUID clazzStatsId, String imgUrl, String groupCode, Boolean hidden) {
        super(Clazz.CLAZZ);

        setId(id);
        setRoomId(roomId);
        setName(name);
        setDescription(description);
        setCode(code);
        setClazzStatsId(clazzStatsId);
        setImgUrl(imgUrl);
        setGroupCode(groupCode);
        setHidden(hidden);
        resetChangedOnNotNull();
    }
}
