/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_2024Race;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_2024RaceRecord extends UpdatableRecordImpl<Default_2024RaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_2024_race.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_2024_race.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_2024_race.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_2024_race.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.default_2024_race.race_stats_id</code>.
     */
    public void setRaceStatsId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.race_stats_id</code>.
     */
    public UUID getRaceStatsId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>rules.default_2024_race.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rules.default_2024_race.species_code</code>.
     */
    public void setSpeciesCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rules.default_2024_race.species_code</code>.
     */
    public String getSpeciesCode() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_2024RaceRecord
     */
    public Default_2024RaceRecord() {
        super(Default_2024Race.DEFAULT_2024_RACE);
    }

    /**
     * Create a detached, initialised Default_2024RaceRecord
     */
    public Default_2024RaceRecord(UUID id, String name, String description, String code, UUID raceStatsId, String imgUrl, String speciesCode) {
        super(Default_2024Race.DEFAULT_2024_RACE);

        setId(id);
        setName(name);
        setDescription(description);
        setCode(code);
        setRaceStatsId(raceStatsId);
        setImgUrl(imgUrl);
        setSpeciesCode(speciesCode);
        resetChangedOnNotNull();
    }
}
