/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClasses;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eClassesRecord extends UpdatableRecordImpl<Default_5eClassesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_5e_classes.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_5e_classes.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_5e_classes.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_5e_classes.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_5e_classes.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_5e_classes.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_5e_classes.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_5e_classes.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.default_5e_classes.class_stats_id</code>.
     */
    public void setClassStatsId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.default_5e_classes.class_stats_id</code>.
     */
    public UUID getClassStatsId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_5eClassesRecord
     */
    public Default_5eClassesRecord() {
        super(Default_5eClasses.DEFAULT_5E_CLASSES);
    }

    /**
     * Create a detached, initialised Default_5eClassesRecord
     */
    public Default_5eClassesRecord(UUID id, String name, String description, String code, UUID classStatsId) {
        super(Default_5eClasses.DEFAULT_5E_CLASSES);

        setId(id);
        setName(name);
        setDescription(description);
        setCode(code);
        setClassStatsId(classStatsId);
        resetChangedOnNotNull();
    }
}
