/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eAbility;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Характеристики существ по дефолтным правилам ДнД 5е
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eAbilityRecord extends UpdatableRecordImpl<Default_5eAbilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_5e_ability.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_5e_ability.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_5e_ability.name</code>. Название
     * Характеристики
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_5e_ability.name</code>. Название
     * Характеристики
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_5e_ability.code</code>. Краткий код
     * Характеристики
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_5e_ability.code</code>. Краткий код
     * Характеристики
     */
    public String getCode() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_5eAbilityRecord
     */
    public Default_5eAbilityRecord() {
        super(Default_5eAbility.DEFAULT_5E_ABILITY);
    }

    /**
     * Create a detached, initialised Default_5eAbilityRecord
     */
    public Default_5eAbilityRecord(UUID id, String name, String code) {
        super(Default_5eAbility.DEFAULT_5E_ABILITY);

        setId(id);
        setName(name);
        setCode(code);
        resetChangedOnNotNull();
    }
}
