/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.DefaultEberronBackground;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Предыстории по умолчанию для сеттинга Eberron (Eberron: Rising from the Last
 * War)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultEberronBackgroundRecord extends UpdatableRecordImpl<DefaultEberronBackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_eberron_background.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_eberron_background.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_eberron_background.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_eberron_background.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_eberron_background.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_eberron_background.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_eberron_background.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_eberron_background.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.default_eberron_background.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.default_eberron_background.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>rules.default_eberron_background.background_stats_id</code>.
     */
    public void setBackgroundStatsId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>rules.default_eberron_background.background_stats_id</code>.
     */
    public UUID getBackgroundStatsId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DefaultEberronBackgroundRecord
     */
    public DefaultEberronBackgroundRecord() {
        super(DefaultEberronBackground.DEFAULT_EBERRON_BACKGROUND);
    }

    /**
     * Create a detached, initialised DefaultEberronBackgroundRecord
     */
    public DefaultEberronBackgroundRecord(UUID id, String name, String description, String code, String imgUrl, UUID backgroundStatsId) {
        super(DefaultEberronBackground.DEFAULT_EBERRON_BACKGROUND);

        setId(id);
        setName(name);
        setDescription(description);
        setCode(code);
        setImgUrl(imgUrl);
        setBackgroundStatsId(backgroundStatsId);
        resetChangedOnNotNull();
    }
}
