/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.DefaultStates;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultStatesRecord extends UpdatableRecordImpl<DefaultStatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_states.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_states.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_states.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_states.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_states.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_states.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_states.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_states.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DefaultStatesRecord
     */
    public DefaultStatesRecord() {
        super(DefaultStates.DEFAULT_STATES);
    }

    /**
     * Create a detached, initialised DefaultStatesRecord
     */
    public DefaultStatesRecord(UUID id, String name, String code, String description) {
        super(DefaultStates.DEFAULT_STATES);

        setId(id);
        setName(name);
        setCode(code);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
