/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eClazz;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eClazzRecord extends UpdatableRecordImpl<Default_5eClazzRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_5e_clazz.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_5e_clazz.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_5e_clazz.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_5e_clazz.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_5e_clazz.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_5e_clazz.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_5e_clazz.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_5e_clazz.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.default_5e_clazz.clazz_stats_id</code>.
     */
    public void setClazzStatsId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.default_5e_clazz.clazz_stats_id</code>.
     */
    public UUID getClazzStatsId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_5eClazzRecord
     */
    public Default_5eClazzRecord() {
        super(Default_5eClazz.DEFAULT_5E_CLAZZ);
    }

    /**
     * Create a detached, initialised Default_5eClazzRecord
     */
    public Default_5eClazzRecord(UUID id, String name, String description, String code, UUID clazzStatsId) {
        super(Default_5eClazz.DEFAULT_5E_CLAZZ);

        setId(id);
        setName(name);
        setDescription(description);
        setCode(code);
        setClazzStatsId(clazzStatsId);
        resetChangedOnNotNull();
    }
}
