/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eSkill;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Навыки по дефолтным правилам DnD 5e
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eSkillRecord extends UpdatableRecordImpl<Default_5eSkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_5e_skill.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_5e_skill.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_5e_skill.name</code>. Название навыка
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_5e_skill.name</code>. Название навыка
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_5e_skill.code</code>. Краткий код навыка
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_5e_skill.code</code>. Краткий код навыка
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_5e_skill.depend_on_ability</code>.
     * Зависимость навыка от характеристики
     */
    public void setDependOnAbility(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_5e_skill.depend_on_ability</code>.
     * Зависимость навыка от характеристики
     */
    public UUID getDependOnAbility() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_5eSkillRecord
     */
    public Default_5eSkillRecord() {
        super(Default_5eSkill.DEFAULT_5E_SKILL);
    }

    /**
     * Create a detached, initialised Default_5eSkillRecord
     */
    public Default_5eSkillRecord(UUID id, String name, String code, UUID dependOnAbility) {
        super(Default_5eSkill.DEFAULT_5E_SKILL);

        setId(id);
        setName(name);
        setCode(code);
        setDependOnAbility(dependOnAbility);
        resetChangedOnNotNull();
    }
}
