/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Default_5eRaces;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Default_5eRacesRecord extends UpdatableRecordImpl<Default_5eRacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.default_5e_races.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.default_5e_races.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.default_5e_races.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.default_5e_races.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.default_5e_races.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.default_5e_races.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.default_5e_races.race_stats_id</code>.
     */
    public void setRaceStatsId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.default_5e_races.race_stats_id</code>.
     */
    public UUID getRaceStatsId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Default_5eRacesRecord
     */
    public Default_5eRacesRecord() {
        super(Default_5eRaces.DEFAULT_5E_RACES);
    }

    /**
     * Create a detached, initialised Default_5eRacesRecord
     */
    public Default_5eRacesRecord(UUID id, String name, String code, UUID raceStatsId) {
        super(Default_5eRaces.DEFAULT_5E_RACES);

        setId(id);
        setName(name);
        setCode(code);
        setRaceStatsId(raceStatsId);
        resetChangedOnNotNull();
    }
}
