/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.RaceStats;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceStatsRecord extends UpdatableRecordImpl<RaceStatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.race_stats.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.race_stats.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.race_stats.max_age</code>.
     */
    public void setMaxAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.race_stats.max_age</code>.
     */
    public Integer getMaxAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rules.race_stats.max_height</code>.
     */
    public void setMaxHeight(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.race_stats.max_height</code>.
     */
    public Integer getMaxHeight() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rules.race_stats.max_weight</code>.
     */
    public void setMaxWeight(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.race_stats.max_weight</code>.
     */
    public Integer getMaxWeight() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>rules.race_stats.base_speed</code>.
     */
    public void setBaseSpeed(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.race_stats.base_speed</code>.
     */
    public Integer getBaseSpeed() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>rules.race_stats.ability_modifiers</code>.
     */
    public void setAbilityModifiers(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.race_stats.ability_modifiers</code>.
     */
    public JSONB getAbilityModifiers() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceStatsRecord
     */
    public RaceStatsRecord() {
        super(RaceStats.RACE_STATS);
    }

    /**
     * Create a detached, initialised RaceStatsRecord
     */
    public RaceStatsRecord(UUID id, Integer maxAge, Integer maxHeight, Integer maxWeight, Integer baseSpeed, JSONB abilityModifiers) {
        super(RaceStats.RACE_STATS);

        setId(id);
        setMaxAge(maxAge);
        setMaxHeight(maxHeight);
        setMaxWeight(maxWeight);
        setBaseSpeed(baseSpeed);
        setAbilityModifiers(abilityModifiers);
        resetChangedOnNotNull();
    }
}
