/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.RaceTraits;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceTraitsRecord extends UpdatableRecordImpl<RaceTraitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.race_traits.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.race_traits.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.race_traits.race_stats_id</code>.
     */
    public void setRaceStatsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.race_traits.race_stats_id</code>.
     */
    public UUID getRaceStatsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.race_traits.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.race_traits.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.race_traits.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.race_traits.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.race_traits.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.race_traits.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceTraitsRecord
     */
    public RaceTraitsRecord() {
        super(RaceTraits.RACE_TRAITS);
    }

    /**
     * Create a detached, initialised RaceTraitsRecord
     */
    public RaceTraitsRecord(UUID id, UUID raceStatsId, String name, String code, String description) {
        super(RaceTraits.RACE_TRAITS);

        setId(id);
        setRaceStatsId(raceStatsId);
        setName(name);
        setCode(code);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
