/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.RaceProficiencies;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RaceProficienciesRecord extends UpdatableRecordImpl<RaceProficienciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.race_proficiencies.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.race_proficiencies.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.race_proficiencies.race_stats_id</code>.
     */
    public void setRaceStatsId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.race_proficiencies.race_stats_id</code>.
     */
    public UUID getRaceStatsId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.race_proficiencies.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.race_proficiencies.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.race_proficiencies.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.race_proficiencies.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RaceProficienciesRecord
     */
    public RaceProficienciesRecord() {
        super(RaceProficiencies.RACE_PROFICIENCIES);
    }

    /**
     * Create a detached, initialised RaceProficienciesRecord
     */
    public RaceProficienciesRecord(UUID id, UUID raceStatsId, String type, String code) {
        super(RaceProficiencies.RACE_PROFICIENCIES);

        setId(id);
        setRaceStatsId(raceStatsId);
        setType(type);
        setCode(code);
        resetChangedOnNotNull();
    }
}
