/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Races;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RacesRecord extends UpdatableRecordImpl<RacesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.races.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.races.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.races.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.races.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.races.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.races.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.races.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.races.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.races.race_stats_id</code>.
     */
    public void setRaceStatsId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.races.race_stats_id</code>.
     */
    public UUID getRaceStatsId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RacesRecord
     */
    public RacesRecord() {
        super(Races.RACES);
    }

    /**
     * Create a detached, initialised RacesRecord
     */
    public RacesRecord(UUID id, UUID roomId, String name, String code, UUID raceStatsId) {
        super(Races.RACES);

        setId(id);
        setRoomId(roomId);
        setName(name);
        setCode(code);
        setRaceStatsId(raceStatsId);
        resetChangedOnNotNull();
    }
}
