/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.RoomRulebookBundle;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomRulebookBundleRecord extends UpdatableRecordImpl<RoomRulebookBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.room_rulebook_bundle.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.room_rulebook_bundle.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.room_rulebook_bundle.rulebook_bundle_id</code>.
     */
    public void setRulebookBundleId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.room_rulebook_bundle.rulebook_bundle_id</code>.
     */
    public UUID getRulebookBundleId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.room_rulebook_bundle.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.room_rulebook_bundle.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomRulebookBundleRecord
     */
    public RoomRulebookBundleRecord() {
        super(RoomRulebookBundle.ROOM_RULEBOOK_BUNDLE);
    }

    /**
     * Create a detached, initialised RoomRulebookBundleRecord
     */
    public RoomRulebookBundleRecord(UUID roomId, UUID rulebookBundleId, LocalDateTime createdAt) {
        super(RoomRulebookBundle.ROOM_RULEBOOK_BUNDLE);

        setRoomId(roomId);
        setRulebookBundleId(rulebookBundleId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
