/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Room;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Реплика информации о комнате из core микросервиса
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoomRecord extends UpdatableRecordImpl<RoomRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.room.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.room.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.room.owner_id</code>. Id владельца комнаты
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.room.owner_id</code>. Id владельца комнаты
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.room.rule_type</code>. Тип правил, например: 4e,
     * 5e, homebrew
     */
    public void setRuleType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.room.rule_type</code>. Тип правил, например: 4e,
     * 5e, homebrew
     */
    public String getRuleType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomRecord
     */
    public RoomRecord() {
        super(Room.ROOM);
    }

    /**
     * Create a detached, initialised RoomRecord
     */
    public RoomRecord(UUID roomId, UUID ownerId, String ruleType) {
        super(Room.ROOM);

        setRoomId(roomId);
        setOwnerId(ownerId);
        setRuleType(ruleType);
        resetChangedOnNotNull();
    }
}
