/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.RulebookBundle;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Наборы правил (издания) для рас/классов/предысторий
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RulebookBundleRecord extends UpdatableRecordImpl<RulebookBundleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.rulebook_bundle.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.edition_code</code>.
     */
    public void setEditionCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.edition_code</code>.
     */
    public String getEditionCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.category</code>.
     */
    public void setCategory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.category</code>.
     */
    public String getCategory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.is_public</code>.
     */
    public void setIsPublic(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.is_public</code>.
     */
    public Boolean getIsPublic() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.owner_user_id</code>.
     */
    public void setOwnerUserId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.owner_user_id</code>.
     */
    public UUID getOwnerUserId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>rules.rulebook_bundle.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>rules.rulebook_bundle.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RulebookBundleRecord
     */
    public RulebookBundleRecord() {
        super(RulebookBundle.RULEBOOK_BUNDLE);
    }

    /**
     * Create a detached, initialised RulebookBundleRecord
     */
    public RulebookBundleRecord(UUID id, String name, String editionCode, String category, String description, String imgUrl, Boolean isPublic, UUID ownerUserId, Integer sortOrder, LocalDateTime createdAt) {
        super(RulebookBundle.RULEBOOK_BUNDLE);

        setId(id);
        setName(name);
        setEditionCode(editionCode);
        setCategory(category);
        setDescription(description);
        setImgUrl(imgUrl);
        setIsPublic(isPublic);
        setOwnerUserId(ownerUserId);
        setSortOrder(sortOrder);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
