/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Skills;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Кастомные навыки существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SkillsRecord extends UpdatableRecordImpl<SkillsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.skills.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.skills.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.skills.name</code>. Название навыка
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.skills.name</code>. Название навыка
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.skills.code</code>. Краткий код навыка
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.skills.code</code>. Краткий код навыка
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.skills.depend_on_ability_id</code>. Зависимость
     * навыка от характеристики
     */
    public void setDependOnAbilityId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.skills.depend_on_ability_id</code>. Зависимость
     * навыка от характеристики
     */
    public UUID getDependOnAbilityId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkillsRecord
     */
    public SkillsRecord() {
        super(Skills.SKILLS);
    }

    /**
     * Create a detached, initialised SkillsRecord
     */
    public SkillsRecord(UUID id, String name, String code, UUID dependOnAbilityId) {
        super(Skills.SKILLS);

        setId(id);
        setName(name);
        setCode(code);
        setDependOnAbilityId(dependOnAbilityId);
        resetChangedOnNotNull();
    }
}
