/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Skill;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Кастомные навыки существ (для homebrew игр)
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SkillRecord extends UpdatableRecordImpl<SkillRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.skill.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.skill.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.skill.name</code>. Название навыка
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.skill.name</code>. Название навыка
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.skill.code</code>. Краткий код навыка
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.skill.code</code>. Краткий код навыка
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.skill.depend_on_ability_id</code>. Зависимость
     * навыка от характеристики
     */
    public void setDependOnAbilityId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.skill.depend_on_ability_id</code>. Зависимость
     * навыка от характеристики
     */
    public UUID getDependOnAbilityId() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkillRecord
     */
    public SkillRecord() {
        super(Skill.SKILL);
    }

    /**
     * Create a detached, initialised SkillRecord
     */
    public SkillRecord(UUID id, String name, String code, UUID dependOnAbilityId) {
        super(Skill.SKILL);

        setId(id);
        setName(name);
        setCode(code);
        setDependOnAbilityId(dependOnAbilityId);
        resetChangedOnNotNull();
    }
}
