/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.Srd_2024Background;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Srd_2024BackgroundRecord extends UpdatableRecordImpl<Srd_2024BackgroundRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.srd_2024_background.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.srd_2024_background.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rules.srd_2024_background.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rules.srd_2024_background.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.srd_2024_background.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rules.srd_2024_background.background_stats_id</code>.
     */
    public void setBackgroundStatsId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.srd_2024_background.background_stats_id</code>.
     */
    public UUID getBackgroundStatsId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Srd_2024BackgroundRecord
     */
    public Srd_2024BackgroundRecord() {
        super(Srd_2024Background.SRD_2024_BACKGROUND);
    }

    /**
     * Create a detached, initialised Srd_2024BackgroundRecord
     */
    public Srd_2024BackgroundRecord(UUID id, String name, String description, String code, String imgUrl, UUID backgroundStatsId) {
        super(Srd_2024Background.SRD_2024_BACKGROUND);

        setId(id);
        setName(name);
        setDescription(description);
        setCode(code);
        setImgUrl(imgUrl);
        setBackgroundStatsId(backgroundStatsId);
        resetChangedOnNotNull();
    }
}
