/*
 * This file is generated by jOOQ.
 */
package com.jiubredeemer.rulebook.dal.entity.tables.records;


import com.jiubredeemer.rulebook.dal.entity.tables.UsersBlueprint;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersBlueprintRecord extends UpdatableRecordImpl<UsersBlueprintRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>rules.users_blueprint.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>rules.users_blueprint.room_id</code>.
     */
    public void setRoomId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.room_id</code>.
     */
    public UUID getRoomId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>rules.users_blueprint.creator_id</code>.
     */
    public void setCreatorId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.creator_id</code>.
     */
    public UUID getCreatorId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>rules.users_blueprint.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rules.users_blueprint.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rules.users_blueprint.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rules.users_blueprint.group_code</code>.
     */
    public void setGroupCode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.group_code</code>.
     */
    public String getGroupCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rules.users_blueprint.required_level</code>.
     */
    public void setRequiredLevel(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.required_level</code>.
     */
    public Integer getRequiredLevel() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>rules.users_blueprint.customization</code>.
     */
    public void setCustomization(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.customization</code>.
     */
    public String getCustomization() {
        return (String) get(8);
    }

    /**
     * Setter for <code>rules.users_blueprint.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>rules.users_blueprint.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>rules.users_blueprint.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>rules.users_blueprint.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>rules.users_blueprint.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersBlueprintRecord
     */
    public UsersBlueprintRecord() {
        super(UsersBlueprint.USERS_BLUEPRINT);
    }

    /**
     * Create a detached, initialised UsersBlueprintRecord
     */
    public UsersBlueprintRecord(UUID id, UUID roomId, UUID creatorId, String code, String name, String description, String groupCode, Integer requiredLevel, String customization, UUID itemId, String imgUrl, Boolean hidden, LocalDateTime createdAt) {
        super(UsersBlueprint.USERS_BLUEPRINT);

        setId(id);
        setRoomId(roomId);
        setCreatorId(creatorId);
        setCode(code);
        setName(name);
        setDescription(description);
        setGroupCode(groupCode);
        setRequiredLevel(requiredLevel);
        setCustomization(customization);
        setItemId(itemId);
        setImgUrl(imgUrl);
        setHidden(hidden);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
